# -*- coding: utf-8 -*-
"""
Dashboard de Mantenimiento Predictivo — Sensores de Bomba Industrial
====================================================================
Versión 3.0 — EDA + ML (XGBoost + validación cruzada) + Pitch integrado.

Pestañas disponibles:
  1. Visión General        — KPIs + serie temporal interactiva
  2. Calidad de Datos      — nulos, duplicados, tipos de datos
  3. Estadística Descriptiva — media, mediana, std, percentiles, IQR
  4. Distribuciones        — histogramas + boxplots individuales
  5. Outliers              — detección por IQR sensor a sensor
  6. Correlaciones         — heatmap + scatter bivariado
  7. Análisis de Clases    — comportamiento por machine_status
  8. Modelo ML (XGBoost)  — entrenamiento, validación cruzada y resultados
  9. Pitch / Presentación  — deck comercial PumpGuard AI

Ejecución local:   python app.py   →   http://127.0.0.1:8050/
"""

from pathlib import Path
import base64

import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from dash import Dash, dcc, html, Input, Output, dash_table
import dash_bootstrap_components as dbc

# --------------------------------------------------------------------------- #
# 1. Carga y preparación de datos
# --------------------------------------------------------------------------- #
DATA_PATH = Path(__file__).parent / "data" / "sensor.csv.gz"

ORDEN_ESTADO = ["NORMAL", "RECOVERING", "BROKEN"]
COLOR_ESTADO  = {"NORMAL": "#2ca02c", "RECOVERING": "#ff7f0e", "BROKEN": "#d62728"}
PALETTE       = px.colors.qualitative.Set2


def cargar_datos() -> pd.DataFrame:
    df = pd.read_csv(DATA_PATH, compression="infer")
    df = df.drop(columns=[c for c in ["Unnamed: 0", "sensor_15"] if c in df.columns])
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df = df.set_index("timestamp").sort_index()
    df["machine_status"] = pd.Categorical(
        df["machine_status"], categories=ORDEN_ESTADO, ordered=True)
    return df


df_raw   = cargar_datos()
df       = df_raw.copy()
sensores = sorted(df.select_dtypes(include="number").columns.tolist())
df[sensores] = df[sensores].interpolate(method="time").ffill().bfill()

FALLAS      = df.index[df["machine_status"] == "BROKEN"]
N_REGISTROS = len(df)
N_SENSORES  = len(sensores)
N_FALLAS    = int((df["machine_status"] == "BROKEN").sum())
RANGO       = f"{df.index.min():%d-%b-%Y}  →  {df.index.max():%d-%b-%Y}"

df_hora      = df[sensores].resample("1h").mean()
estado_hora  = (
    df["machine_status"].astype(str)
    .resample("1h")
    .agg(lambda x: x.mode().iat[0] if len(x) else "NORMAL")
)

desc = df[sensores].describe(percentiles=[.25, .5, .75, .95]).T.round(4)
desc["IQR"]     = desc["75%"] - desc["25%"]
desc["missing"] = df_raw[sensores].isnull().sum()
desc["missing%"]= (desc["missing"] / N_REGISTROS * 100).round(2)
desc = desc.rename(columns={"50%": "median"})
desc = desc.reset_index().rename(columns={"index": "sensor"})

nulos_por_col = df_raw.isnull().sum().reset_index()
nulos_por_col.columns = ["columna", "nulos"]
nulos_por_col["porcentaje"] = (nulos_por_col["nulos"] / N_REGISTROS * 100).round(2)
nulos_por_col = nulos_por_col.sort_values("nulos", ascending=False)

tipos_df = df_raw.dtypes.reset_index()
tipos_df.columns = ["columna", "tipo"]
tipos_df["tipo"] = tipos_df["tipo"].astype(str)

corr_matrix = df[sensores].corr()

# --------------------------------------------------------------------------- #
# 2. Preparación del modelo XGBoost
# --------------------------------------------------------------------------- #
def preparar_datos_ml(df_in, sensores_in):
    """Construye X e y para clasificación binaria NORMAL vs Anómalo."""
    df_reset = df_in.reset_index()
    X = df_reset[sensores_in].copy()
    y = (df_reset["machine_status"].astype(str)
         .isin(["RECOVERING", "BROKEN"])).astype(int)
    return X, y


# Submuestreo estratificado para velocidad en el dashboard (50 k filas)
SAMPLE_ML = 50_000
df_ml = df.copy()
if len(df_ml) > SAMPLE_ML:
    df_ml = df_ml.groupby("machine_status", group_keys=False, observed=True).apply(
        lambda g: g.sample(min(len(g), int(SAMPLE_ML * len(g) / len(df_ml))),
                           random_state=42))

X_ml, y_ml = preparar_datos_ml(df_ml, sensores)

# Split cronológico (80 % pasado / 20 % futuro)
split_idx   = int(len(X_ml) * 0.8)
X_train_ml  = X_ml.iloc[:split_idx]
X_test_ml   = X_ml.iloc[split_idx:]
y_train_ml  = y_ml.iloc[:split_idx]
y_test_ml   = y_ml.iloc[split_idx:]

# Razón de desbalance para scale_pos_weight
razon_clases = max((y_train_ml == 0).sum() / max((y_train_ml == 1).sum(), 1), 1)

# Entrenamiento XGBoost con mejores hiperparámetros (del notebook GridSearch)
try:
    from xgboost import XGBClassifier
    from sklearn.model_selection import StratifiedKFold, cross_val_score
    from sklearn.metrics import (f1_score, roc_auc_score, precision_score,
                                 recall_score, confusion_matrix,
                                 classification_report)

    xgb_model = XGBClassifier(
        n_estimators=400,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        scale_pos_weight=razon_clases,
        eval_metric="logloss",
        tree_method="hist",
        n_jobs=-1,
        random_state=42,
        verbosity=0,
    )
    xgb_model.fit(X_train_ml.values, y_train_ml)

    y_pred_ml   = xgb_model.predict(X_test_ml.values)
    y_proba_ml  = xgb_model.predict_proba(X_test_ml.values)[:, 1]

    # Validación cruzada estratificada (5-fold) sobre submuestreo
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    cv_f1  = cross_val_score(xgb_model, X_ml.values, y_ml, cv=skf,
                             scoring="f1",      n_jobs=-1)
    cv_auc = cross_val_score(xgb_model, X_ml.values, y_ml, cv=skf,
                             scoring="roc_auc", n_jobs=-1)

    ML_METRICAS = {
        "F1 (test cronológico)":  round(f1_score(y_test_ml, y_pred_ml), 4),
        "ROC-AUC (test)":         round(roc_auc_score(y_test_ml, y_proba_ml), 4),
        "Precision (test)":       round(precision_score(y_test_ml, y_pred_ml, zero_division=0), 4),
        "Recall (test)":          round(recall_score(y_test_ml, y_pred_ml, zero_division=0), 4),
        "F1 CV media (5-fold)":   round(cv_f1.mean(), 4),
        "F1 CV std  (5-fold)":    round(cv_f1.std(),  4),
        "AUC CV media (5-fold)":  round(cv_auc.mean(), 4),
        "AUC CV std  (5-fold)":   round(cv_auc.std(),  4),
    }
    ML_CM      = confusion_matrix(y_test_ml, y_pred_ml)
    ML_CV_F1   = cv_f1
    ML_CV_AUC  = cv_auc
    ML_IMPORTANCIAS = pd.Series(
        xgb_model.feature_importances_, index=sensores
    ).sort_values(ascending=False)
    ML_OK = True

except ImportError:
    ML_OK = False
    ML_METRICAS = {"Error": "xgboost no instalado — ejecute: pip install xgboost"}
    ML_CM = None
    ML_CV_F1 = ML_CV_AUC = None
    ML_IMPORTANCIAS = None

# --------------------------------------------------------------------------- #
# 3. Pitch HTML embebido en base64
# --------------------------------------------------------------------------- #
PITCH_B64 = "PCFET0NUWVBFIGh0bWw+CjxodG1sIGxhbmc9ImVzIj4KPGhlYWQ+CjxtZXRhIGNoYXJzZXQ9IlVURi04Ij4KPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPgo8dGl0bGU+UHVtcEd1YXJkIEFJIOKAlCBEZXRlY2Npw7NuIGRlIEFub21hbMOtYXM8L3RpdGxlPgo8bGluayBocmVmPSJodHRwczovL2ZvbnRzLmdvb2dsZWFwaXMuY29tL2NzczI/ZmFtaWx5PVNwYWNlK0dyb3Rlc2s6d2dodEAzMDA7NDAwOzUwMDs2MDA7NzAwJmZhbWlseT1JbnRlcjp3Z2h0QDMwMDs0MDA7NTAwJmRpc3BsYXk9c3dhcCIgcmVsPSJzdHlsZXNoZWV0Ij4KPHN0eWxlPgogICosICo6OmJlZm9yZSwgKjo6YWZ0ZXIgeyBib3gtc2l6aW5nOiBib3JkZXItYm94OyBtYXJnaW46IDA7IHBhZGRpbmc6IDA7IH0KCiAgOnJvb3QgewogICAgLS1iZzogIzBBMEEwRjsKICAgIC0tc3VyZmFjZTogIzEyMTIxQTsKICAgIC0tYm9yZGVyOiAjMUUxRTJFOwogICAgLS1vcmFuZ2U6ICNGRjVDMDA7CiAgICAtLWdyZWVuOiAjMDBFODdBOwogICAgLS15ZWxsb3c6ICNGRkQxMDA7CiAgICAtLXRleHQ6ICNGMEYwRjU7CiAgICAtLW11dGVkOiAjNkI2QjgwOwogICAgLS1mb250LWRpc3BsYXk6ICdTcGFjZSBHcm90ZXNrJywgc2Fucy1zZXJpZjsKICAgIC0tZm9udC1ib2R5OiAnSW50ZXInLCBzYW5zLXNlcmlmOwogIH0KCiAgaHRtbCwgYm9keSB7CiAgICB3aWR0aDogMTAwJTsgaGVpZ2h0OiAxMDAlOwogICAgYmFja2dyb3VuZDogdmFyKC0tYmcpOwogICAgY29sb3I6IHZhcigtLXRleHQpOwogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtYm9keSk7CiAgICBvdmVyZmxvdzogaGlkZGVuOwogIH0KCiAgLyog4pSA4pSAIFNMSURFIFNZU1RFTSDilIDilIAgKi8KICAuZGVjayB7IHdpZHRoOiAxMDB2dzsgaGVpZ2h0OiAxMDB2aDsgcG9zaXRpb246IHJlbGF0aXZlOyB9CiAgLnNsaWRlIHsKICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsgaW5zZXQ6IDA7CiAgICBkaXNwbGF5OiBmbGV4OyBmbGV4LWRpcmVjdGlvbjogY29sdW1uOwogICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7IGFsaWduLWl0ZW1zOiBjZW50ZXI7CiAgICBwYWRkaW5nOiA0cmVtOwogICAgb3BhY2l0eTogMDsgcG9pbnRlci1ldmVudHM6IG5vbmU7CiAgICB0cmFuc2l0aW9uOiBvcGFjaXR5IDAuNnMgZWFzZSwgdHJhbnNmb3JtIDAuNnMgZWFzZTsKICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgzMHB4KTsKICB9CiAgLnNsaWRlLmFjdGl2ZSB7CiAgICBvcGFjaXR5OiAxOyBwb2ludGVyLWV2ZW50czogYWxsOyB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMCk7CiAgfQogIC5zbGlkZS5leGl0IHsKICAgIG9wYWNpdHk6IDA7IHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMzBweCk7CiAgfQoKICAvKiDilIDilIAgTkFWIOKUgOKUgCAqLwogIC5uYXYgewogICAgcG9zaXRpb246IGZpeGVkOyBib3R0b206IDJyZW07IGxlZnQ6IDUwJTsgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKC01MCUpOwogICAgZGlzcGxheTogZmxleDsgZ2FwOiAwLjVyZW07IHotaW5kZXg6IDEwMDsKICB9CiAgLmRvdCB7CiAgICB3aWR0aDogOHB4OyBoZWlnaHQ6IDhweDsgYm9yZGVyLXJhZGl1czogNTAlOwogICAgYmFja2dyb3VuZDogdmFyKC0tYm9yZGVyKTsgY3Vyc29yOiBwb2ludGVyOwogICAgdHJhbnNpdGlvbjogYmFja2dyb3VuZCAwLjNzLCB0cmFuc2Zvcm0gMC4zczsKICB9CiAgLmRvdC5hY3RpdmUgeyBiYWNrZ3JvdW5kOiB2YXIoLS1vcmFuZ2UpOyB0cmFuc2Zvcm06IHNjYWxlKDEuNCk7IH0KCiAgLm5hdi1hcnJvd3MgewogICAgcG9zaXRpb246IGZpeGVkOyBib3R0b206IDJyZW07IHJpZ2h0OiAyLjVyZW07CiAgICBkaXNwbGF5OiBmbGV4OyBnYXA6IDAuNzVyZW07IHotaW5kZXg6IDEwMDsKICB9CiAgLmJ0bi1uYXYgewogICAgd2lkdGg6IDQ0cHg7IGhlaWdodDogNDRweDsgYm9yZGVyLXJhZGl1czogNTAlOwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGJhY2tncm91bmQ6IHZhcigtLXN1cmZhY2UpOwogICAgY29sb3I6IHZhcigtLXRleHQpOyBmb250LXNpemU6IDEuMXJlbTsKICAgIGN1cnNvcjogcG9pbnRlcjsgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICB0cmFuc2l0aW9uOiBib3JkZXItY29sb3IgMC4ycywgYmFja2dyb3VuZCAwLjJzOwogIH0KICAuYnRuLW5hdjpob3ZlciB7IGJvcmRlci1jb2xvcjogdmFyKC0tb3JhbmdlKTsgYmFja2dyb3VuZDogIzFhMWEyNDsgfQoKICAuc2xpZGUtY291bnRlciB7CiAgICBwb3NpdGlvbjogZml4ZWQ7IHRvcDogMnJlbTsgcmlnaHQ6IDIuNXJlbTsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjc1cmVtOyBjb2xvcjogdmFyKC0tbXV0ZWQpOwogICAgbGV0dGVyLXNwYWNpbmc6IDAuMTVlbTsKICB9CiAgLnNsaWRlLWNvdW50ZXIgc3BhbiB7IGNvbG9yOiB2YXIoLS1vcmFuZ2UpOyB9CgogIC8qIOKUgOKUgCBMT0dPIEJBUiDilIDilIAgKi8KICAubG9nby1iYXIgewogICAgcG9zaXRpb246IGZpeGVkOyB0b3A6IDJyZW07IGxlZnQ6IDIuNXJlbTsKICAgIGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGdhcDogMC42cmVtOwogICAgei1pbmRleDogMTAwOwogIH0KICAubG9nby1pY29uIHsKICAgIHdpZHRoOiAyOHB4OyBoZWlnaHQ6IDI4cHg7CiAgICBib3JkZXI6IDJweCBzb2xpZCB2YXIoLS1vcmFuZ2UpOwogICAgYm9yZGVyLXJhZGl1czogNnB4OwogICAgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsganVzdGlmeS1jb250ZW50OiBjZW50ZXI7CiAgICBmb250LXNpemU6IDAuOHJlbTsKICB9CiAgLmxvZ28tdGV4dCB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogMC44NXJlbTsgZm9udC13ZWlnaHQ6IDYwMDsKICAgIGxldHRlci1zcGFjaW5nOiAwLjA1ZW07CiAgfQogIC5sb2dvLXRleHQgZW0geyBjb2xvcjogdmFyKC0tb3JhbmdlKTsgZm9udC1zdHlsZTogbm9ybWFsOyB9CgogIC8qIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgAogICAgIFNMSURFIDEg4oCUIEhFUk8KICDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAjczEgeyBiYWNrZ3JvdW5kOiB2YXIoLS1iZyk7IH0KCiAgLmhlcm8tZXllYnJvdyB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogMC43MnJlbTsgZm9udC13ZWlnaHQ6IDUwMDsKICAgIGxldHRlci1zcGFjaW5nOiAwLjI1ZW07IHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7CiAgICBjb2xvcjogdmFyKC0tb3JhbmdlKTsKICAgIG1hcmdpbi1ib3R0b206IDEuNXJlbTsKICAgIGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGdhcDogMC42cmVtOwogIH0KICAuaGVyby1leWVicm93OjpiZWZvcmUgewogICAgY29udGVudDogJyc7IGRpc3BsYXk6IGJsb2NrOwogICAgd2lkdGg6IDMycHg7IGhlaWdodDogMXB4OyBiYWNrZ3JvdW5kOiB2YXIoLS1vcmFuZ2UpOwogIH0KCiAgLmhlcm8tdGl0bGUgewogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICBmb250LXNpemU6IGNsYW1wKDNyZW0sIDZ2dywgNS41cmVtKTsKICAgIGZvbnQtd2VpZ2h0OiA3MDA7IGxpbmUtaGVpZ2h0OiAxLjA1OwogICAgbGV0dGVyLXNwYWNpbmc6IC0wLjAyZW07CiAgICB0ZXh0LWFsaWduOiBjZW50ZXI7CiAgICBtYXJnaW4tYm90dG9tOiAxLjVyZW07CiAgfQogIC5oZXJvLXRpdGxlIC5hY2NlbnQgeyBjb2xvcjogdmFyKC0tb3JhbmdlKTsgfQogIC5oZXJvLXRpdGxlIC5kaW0geyBjb2xvcjogdmFyKC0tbXV0ZWQpOyBmb250LXdlaWdodDogMzAwOyB9CgogIC5oZXJvLXN1YiB7CiAgICBmb250LXNpemU6IDEuMXJlbTsgY29sb3I6IHZhcigtLW11dGVkKTsKICAgIG1heC13aWR0aDogNTIwcHg7IHRleHQtYWxpZ246IGNlbnRlcjsKICAgIGxpbmUtaGVpZ2h0OiAxLjY7CiAgICBtYXJnaW4tYm90dG9tOiAzcmVtOwogIH0KCiAgLyogR2F1Z2UgKi8KICAuZ2F1Z2Utd3JhcCB7CiAgICBwb3NpdGlvbjogcmVsYXRpdmU7IHdpZHRoOiAyMjBweDsgaGVpZ2h0OiAxMzBweDsKICAgIG1hcmdpbi1ib3R0b206IDIuNXJlbTsKICB9CiAgLmdhdWdlLXdyYXAgY2FudmFzIHsgcG9zaXRpb246IGFic29sdXRlOyB0b3A6IDA7IGxlZnQ6IDA7IH0KICAuZ2F1Z2UtbGFiZWwgewogICAgcG9zaXRpb246IGFic29sdXRlOyBib3R0b206IDA7IGxlZnQ6IDUwJTsKICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWCgtNTAlKTsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjY1cmVtOyBsZXR0ZXItc3BhY2luZzogMC4xMmVtOwogICAgY29sb3I6IHZhcigtLW11dGVkKTsgdGV4dC10cmFuc2Zvcm06IHVwcGVyY2FzZTsKICB9CiAgLmdhdWdlLXZhbHVlIHsKICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTsgdG9wOiA2MCU7IGxlZnQ6IDUwJTsKICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlKC01MCUsIC01MCUpOwogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICBmb250LXNpemU6IDEuNnJlbTsgZm9udC13ZWlnaHQ6IDcwMDsKICAgIGNvbG9yOiB2YXIoLS10ZXh0KTsKICB9CgogIC5oZXJvLXRhZ3MgewogICAgZGlzcGxheTogZmxleDsgZ2FwOiAwLjc1cmVtOyBmbGV4LXdyYXA6IHdyYXA7IGp1c3RpZnktY29udGVudDogY2VudGVyOwogIH0KICAudGFnIHsKICAgIHBhZGRpbmc6IDAuMzVyZW0gMC45cmVtOwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGJvcmRlci1yYWRpdXM6IDk5OXB4OwogICAgZm9udC1zaXplOiAwLjc1cmVtOyBjb2xvcjogdmFyKC0tbXV0ZWQpOwogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgfQoKICAvKiDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKICAgICBTTElERSAyIOKAlCBQUk9CTEVNQQogIOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgOKUgCAqLwogICNzMiB7IGJhY2tncm91bmQ6IHZhcigtLWJnKTsgfQoKICAudHdvLWNvbCB7CiAgICBkaXNwbGF5OiBncmlkOyBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmciAxZnI7CiAgICBnYXA6IDRyZW07IHdpZHRoOiAxMDAlOyBtYXgtd2lkdGg6IDkwMHB4OwogICAgYWxpZ24taXRlbXM6IGNlbnRlcjsKICB9CgogIC5zdGF0LXN0YWNrIHsgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgZ2FwOiAycmVtOyB9CiAgLmJpZy1zdGF0IHsKICAgIGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGdhcDogMC4yNXJlbTsKICB9CiAgLmJpZy1zdGF0IC5udW0gewogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICBmb250LXNpemU6IGNsYW1wKDMuNXJlbSwgNXZ3LCA1cmVtKTsKICAgIGZvbnQtd2VpZ2h0OiA3MDA7IGxpbmUtaGVpZ2h0OiAxOwogICAgY29sb3I6IHZhcigtLW9yYW5nZSk7CiAgfQogIC5iaWctc3RhdCAubGFiZWwgewogICAgZm9udC1zaXplOiAwLjg1cmVtOyBjb2xvcjogdmFyKC0tbXV0ZWQpOyBtYXgtd2lkdGg6IDIyMHB4OwogICAgbGluZS1oZWlnaHQ6IDEuNDsKICB9CiAgLmRpdmlkZXItaCB7IHdpZHRoOiA0MHB4OyBoZWlnaHQ6IDFweDsgYmFja2dyb3VuZDogdmFyKC0tYm9yZGVyKTsgfQoKICAucGFpbi1saXN0IHsgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgZ2FwOiAxLjI1cmVtOyB9CiAgLnBhaW4taXRlbSB7CiAgICBkaXNwbGF5OiBmbGV4OyBnYXA6IDFyZW07IGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0OwogICAgcGFkZGluZzogMXJlbSAxLjJyZW07CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgYm9yZGVyLXJhZGl1czogMTBweDsKICAgIGJhY2tncm91bmQ6IHZhcigtLXN1cmZhY2UpOwogICAgdHJhbnNpdGlvbjogYm9yZGVyLWNvbG9yIDAuM3M7CiAgfQogIC5wYWluLWl0ZW06aG92ZXIgeyBib3JkZXItY29sb3I6IHZhcigtLW9yYW5nZSk7IH0KICAucGFpbi1pY29uIHsgZm9udC1zaXplOiAxLjNyZW07IGZsZXgtc2hyaW5rOiAwOyBtYXJnaW4tdG9wOiAwLjFyZW07IH0KICAucGFpbi10ZXh0IHN0cm9uZyB7CiAgICBkaXNwbGF5OiBibG9jazsgZm9udC1zaXplOiAwLjlyZW07IGZvbnQtd2VpZ2h0OiA2MDA7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsgbWFyZ2luLWJvdHRvbTogMC4ycmVtOwogIH0KICAucGFpbi10ZXh0IHNwYW4geyBmb250LXNpemU6IDAuOHJlbTsgY29sb3I6IHZhcigtLW11dGVkKTsgfQoKICAuc2VjdGlvbi10aXRsZSB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogY2xhbXAoMnJlbSwgMy41dncsIDNyZW0pOwogICAgZm9udC13ZWlnaHQ6IDcwMDsgbGluZS1oZWlnaHQ6IDEuMTsKICAgIG1hcmdpbi1ib3R0b206IDJyZW07CiAgICBsZXR0ZXItc3BhY2luZzogLTAuMDJlbTsKICB9CiAgLnNlY3Rpb24tdGl0bGUgLm9yYW5nZSB7IGNvbG9yOiB2YXIoLS1vcmFuZ2UpOyB9CiAgLnNlY3Rpb24tdGl0bGUgLmdyZWVuIHsgY29sb3I6IHZhcigtLWdyZWVuKTsgfQoKICAvKiDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKICAgICBTTElERSAzIOKAlCBTT0xVQ0nDk04KICDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAjczMgeyBiYWNrZ3JvdW5kOiB2YXIoLS1iZyk7IH0KCiAgLnNvbHV0aW9uLWdyaWQgewogICAgZGlzcGxheTogZ3JpZDsKICAgIGdyaWQtdGVtcGxhdGUtY29sdW1uczogcmVwZWF0KDMsIDFmcik7CiAgICBnYXA6IDEuMjVyZW07CiAgICB3aWR0aDogMTAwJTsgbWF4LXdpZHRoOiA4NjBweDsKICAgIG1hcmdpbi10b3A6IDJyZW07CiAgfQogIC5zb2wtY2FyZCB7CiAgICBwYWRkaW5nOiAxLjVyZW07CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgYm9yZGVyLXJhZGl1czogMTRweDsKICAgIGJhY2tncm91bmQ6IHZhcigtLXN1cmZhY2UpOwogICAgdHJhbnNpdGlvbjogdHJhbnNmb3JtIDAuM3MsIGJvcmRlci1jb2xvciAwLjNzOwogICAgY3Vyc29yOiBkZWZhdWx0OwogIH0KICAuc29sLWNhcmQ6aG92ZXIgeyB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTRweCk7IGJvcmRlci1jb2xvcjogdmFyKC0tZ3JlZW4pOyB9CiAgLnNvbC1jYXJkIC5zb2wtaWNvbiB7CiAgICBmb250LXNpemU6IDEuOHJlbTsgbWFyZ2luLWJvdHRvbTogMC43NXJlbTsKICB9CiAgLnNvbC1jYXJkIGgzIHsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjk1cmVtOyBmb250LXdlaWdodDogNjAwOwogICAgbWFyZ2luLWJvdHRvbTogMC41cmVtOwogIH0KICAuc29sLWNhcmQgcCB7IGZvbnQtc2l6ZTogMC43OHJlbTsgY29sb3I6IHZhcigtLW11dGVkKTsgbGluZS1oZWlnaHQ6IDEuNTsgfQogIC5zb2wtY2FyZCAuYmFkZ2UgewogICAgZGlzcGxheTogaW5saW5lLWJsb2NrOyBtYXJnaW4tdG9wOiAwLjc1cmVtOwogICAgcGFkZGluZzogMC4ycmVtIDAuNnJlbTsKICAgIGJvcmRlci1yYWRpdXM6IDk5OXB4OwogICAgZm9udC1zaXplOiAwLjY1cmVtOyBmb250LXdlaWdodDogNjAwOwogICAgbGV0dGVyLXNwYWNpbmc6IDAuMDhlbTsKICAgIGJhY2tncm91bmQ6IHJnYmEoMCwgMjMyLCAxMjIsIDAuMTIpOwogICAgY29sb3I6IHZhcigtLWdyZWVuKTsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogIH0KCiAgLnBpcGVsaW5lIHsKICAgIGRpc3BsYXk6IGZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGdhcDogMC41cmVtOwogICAgbWFyZ2luLXRvcDogMnJlbTsKICAgIHBhZGRpbmc6IDFyZW0gMS41cmVtOwogICAgYm9yZGVyOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGJvcmRlci1yYWRpdXM6IDEwcHg7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1zdXJmYWNlKTsKICAgIHdpZHRoOiAxMDAlOyBtYXgtd2lkdGg6IDg2MHB4OwogICAgZmxleC13cmFwOiB3cmFwOyBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICB9CiAgLnBpcGUtc3RlcCB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogMC43NXJlbTsgZm9udC13ZWlnaHQ6IDUwMDsKICAgIGNvbG9yOiB2YXIoLS1tdXRlZCk7CiAgICB3aGl0ZS1zcGFjZTogbm93cmFwOwogIH0KICAucGlwZS1hcnJvdyB7IGNvbG9yOiB2YXIoLS1vcmFuZ2UpOyBmb250LXNpemU6IDAuOXJlbTsgfQogIC5waXBlLXN0ZXAuaGlnaGxpZ2h0IHsgY29sb3I6IHZhcigtLW9yYW5nZSk7IGZvbnQtd2VpZ2h0OiA3MDA7IH0KCiAgLyog4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSACiAgICAgU0xJREUgNCDigJQgTcOJVFJJQ0FTCiAg4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSA4pSAICovCiAgI3M0IHsKICAgIGJhY2tncm91bmQ6IHJhZGlhbC1ncmFkaWVudChlbGxpcHNlIGF0IDcwJSAzMCUsIHJnYmEoMCwyMzIsMTIyLDAuMDQpIDAlLCB0cmFuc3BhcmVudCA2MCUpLCB2YXIoLS1iZyk7CiAgfQoKICAubWV0cmljcy1sYXlvdXQgewogICAgZGlzcGxheTogZ3JpZDsgZ3JpZC10ZW1wbGF0ZS1jb2x1bW5zOiAxZnIgMS40ZnI7CiAgICBnYXA6IDNyZW07IHdpZHRoOiAxMDAlOyBtYXgtd2lkdGg6IDkwMHB4OyBhbGlnbi1pdGVtczogY2VudGVyOwogIH0KCiAgLm1ldHJpYy1jYXJkcyB7IGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGdhcDogMXJlbTsgfQogIC5tLWNhcmQgewogICAgcGFkZGluZzogMS4yNXJlbSAxLjVyZW07CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgYm9yZGVyLXJhZGl1czogMTJweDsKICAgIGJhY2tncm91bmQ6IHZhcigtLXN1cmZhY2UpOwogICAgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsgZ2FwOiAxLjI1cmVtOwogIH0KICAubS1jYXJkIC5tLXZhbCB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogMi40cmVtOyBmb250LXdlaWdodDogNzAwOwogICAgY29sb3I6IHZhcigtLWdyZWVuKTsgZmxleC1zaHJpbms6IDA7CiAgICBsaW5lLWhlaWdodDogMTsKICB9CiAgLm0tY2FyZCAubS1pbmZvIHN0cm9uZyB7CiAgICBkaXNwbGF5OiBibG9jazsKICAgIGZvbnQtc2l6ZTogMC44NXJlbTsgZm9udC13ZWlnaHQ6IDYwMDsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgbWFyZ2luLWJvdHRvbTogMC4ycmVtOwogIH0KICAubS1jYXJkIC5tLWluZm8gc3BhbiB7IGZvbnQtc2l6ZTogMC43NXJlbTsgY29sb3I6IHZhcigtLW11dGVkKTsgfQoKICAuYmFyLWNoYXJ0IHsgd2lkdGg6IDEwMCU7IH0KICAuYmFyLWNoYXJ0IGg0IHsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjc1cmVtOyBjb2xvcjogdmFyKC0tbXV0ZWQpOwogICAgbGV0dGVyLXNwYWNpbmc6IDAuMWVtOyB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOwogICAgbWFyZ2luLWJvdHRvbTogMS4yNXJlbTsKICB9CiAgLmJhci1yb3cgewogICAgZGlzcGxheTogZmxleDsgYWxpZ24taXRlbXM6IGNlbnRlcjsgZ2FwOiAwLjc1cmVtOwogICAgbWFyZ2luLWJvdHRvbTogMXJlbTsKICB9CiAgLmJhci1uYW1lIHsKICAgIGZvbnQtc2l6ZTogMC43NXJlbTsgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICB3aWR0aDogOTBweDsgZmxleC1zaHJpbms6IDA7IHRleHQtYWxpZ246IHJpZ2h0OyBjb2xvcjogdmFyKC0tbXV0ZWQpOwogIH0KICAuYmFyLXRyYWNrIHsKICAgIGZsZXg6IDE7IGhlaWdodDogMTBweDsgYmFja2dyb3VuZDogdmFyKC0tYm9yZGVyKTsgYm9yZGVyLXJhZGl1czogOTk5cHg7IG92ZXJmbG93OiBoaWRkZW47CiAgfQogIC5iYXItZmlsbCB7CiAgICBoZWlnaHQ6IDEwMCU7IGJvcmRlci1yYWRpdXM6IDk5OXB4OwogICAgd2lkdGg6IDA7CiAgICB0cmFuc2l0aW9uOiB3aWR0aCAxLjJzIGN1YmljLWJlemllcigwLjQsMCwwLjIsMSk7CiAgfQogIC5iYXItcGN0IHsKICAgIGZvbnQtc2l6ZTogMC43MnJlbTsgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7IGZvbnQtd2VpZ2h0OiA2MDA7CiAgICB3aWR0aDogMzhweDsgZmxleC1zaHJpbms6IDA7CiAgfQoKICAvKiDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKICAgICBTTElERSA1IOKAlCBBTEVSVEFTIEVOIFZJVk8KICDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAjczUgeyBiYWNrZ3JvdW5kOiB2YXIoLS1iZyk7IH0KCiAgLmFsZXJ0LWRlbW8gewogICAgd2lkdGg6IDEwMCU7IG1heC13aWR0aDogODYwcHg7CiAgICBkaXNwbGF5OiBncmlkOyBncmlkLXRlbXBsYXRlLWNvbHVtbnM6IDFmciAxZnI7CiAgICBnYXA6IDJyZW07IG1hcmdpbi10b3A6IDEuNXJlbTsKICB9CiAgLmFsZXJ0LXBhbmVsIHsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7IGJvcmRlci1yYWRpdXM6IDE0cHg7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1zdXJmYWNlKTsgcGFkZGluZzogMS41cmVtOwogICAgZGlzcGxheTogZmxleDsgZmxleC1kaXJlY3Rpb246IGNvbHVtbjsgZ2FwOiAwLjc1cmVtOwogIH0KICAuYWxlcnQtcGFuZWwgaDQgewogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICBmb250LXNpemU6IDAuN3JlbTsgbGV0dGVyLXNwYWNpbmc6IDAuMTVlbTsKICAgIHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7IGNvbG9yOiB2YXIoLS1tdXRlZCk7CiAgICBtYXJnaW4tYm90dG9tOiAwLjI1cmVtOwogIH0KICAuYWxlcnQtbG9nIHsKICAgIGRpc3BsYXk6IGZsZXg7IGZsZXgtZGlyZWN0aW9uOiBjb2x1bW47IGdhcDogMC41cmVtOwogICAgbWF4LWhlaWdodDogMjQwcHg7IG92ZXJmbG93OiBoaWRkZW47CiAgfQogIC5hbGVydC1lbnRyeSB7CiAgICBkaXNwbGF5OiBmbGV4OyBhbGlnbi1pdGVtczogY2VudGVyOyBnYXA6IDAuN3JlbTsKICAgIHBhZGRpbmc6IDAuNXJlbSAwLjc1cmVtOwogICAgYm9yZGVyLXJhZGl1czogOHB4OwogICAgZm9udC1zaXplOiAwLjc1cmVtOwogICAgYW5pbWF0aW9uOiBzbGlkZUluIDAuNHMgZWFzZTsKICB9CiAgQGtleWZyYW1lcyBzbGlkZUluIHsKICAgIGZyb20geyBvcGFjaXR5OiAwOyB0cmFuc2Zvcm06IHRyYW5zbGF0ZVgoLTEwcHgpOyB9CiAgICB0byAgIHsgb3BhY2l0eTogMTsgdHJhbnNmb3JtOiB0cmFuc2xhdGVYKDApOyB9CiAgfQogIC5hbGVydC1lbnRyeS5ub3JtYWwgIHsgYmFja2dyb3VuZDogcmdiYSgwLDIzMiwxMjIsMC4wOCk7IH0KICAuYWxlcnQtZW50cnkubWVkaW8gICB7IGJhY2tncm91bmQ6IHJnYmEoMjU1LDIwOSwwLDAuMDgpOyB9CiAgLmFsZXJ0LWVudHJ5LmFsdG8gICAgeyBiYWNrZ3JvdW5kOiByZ2JhKDI1NSw5MiwwLDAuMSk7IH0KICAuYWxlcnQtZW50cnkgLmFsLXRpbWUgeyBjb2xvcjogdmFyKC0tbXV0ZWQpOyBmb250LXNpemU6IDAuNjVyZW07IGZsZXgtc2hyaW5rOiAwOyB9CiAgLmFsZXJ0LWVudHJ5IC5hbC1zdGF0dXMgeyBmb250LXdlaWdodDogNjAwOyBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsgfQoKICAub3V0cHV0LXBhbmVsIHsKICAgIGJvcmRlcjogMXB4IHNvbGlkIHZhcigtLWJvcmRlcik7IGJvcmRlci1yYWRpdXM6IDE0cHg7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1zdXJmYWNlKTsgcGFkZGluZzogMS41cmVtOwogICAgZm9udC1mYW1pbHk6ICdTcGFjZSBHcm90ZXNrJywgbW9ub3NwYWNlOwogIH0KICAub3V0cHV0LXBhbmVsIGg0IHsKICAgIGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjdyZW07IGxldHRlci1zcGFjaW5nOiAwLjE1ZW07CiAgICB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOyBjb2xvcjogdmFyKC0tbXV0ZWQpOyBtYXJnaW4tYm90dG9tOiAxcmVtOwogIH0KICAub3V0LXJvdyB7CiAgICBkaXNwbGF5OiBmbGV4OyBqdXN0aWZ5LWNvbnRlbnQ6IHNwYWNlLWJldHdlZW47CiAgICBhbGlnbi1pdGVtczogY2VudGVyOwogICAgcGFkZGluZzogMC42cmVtIDA7CiAgICBib3JkZXItYm90dG9tOiAxcHggc29saWQgdmFyKC0tYm9yZGVyKTsKICAgIGZvbnQtc2l6ZTogMC44cmVtOwogIH0KICAub3V0LXJvdzpsYXN0LWNoaWxkIHsgYm9yZGVyLWJvdHRvbTogbm9uZTsgfQogIC5vdXQta2V5IHsgY29sb3I6IHZhcigtLW11dGVkKTsgfQogIC5vdXQtdmFsIHsgZm9udC13ZWlnaHQ6IDYwMDsgfQogIC5vdXQtdmFsLm5vcm1hbCB7IGNvbG9yOiB2YXIoLS1ncmVlbik7IH0KICAub3V0LXZhbC5hbm9tYWxvIHsgY29sb3I6IHZhcigtLW9yYW5nZSk7IH0KICAub3V0LXZhbC5iYWpvICB7IGNvbG9yOiB2YXIoLS1ncmVlbik7IH0KICAub3V0LXZhbC5tZWRpbyB7IGNvbG9yOiB2YXIoLS15ZWxsb3cpOyB9CiAgLm91dC12YWwuYWx0byAgeyBjb2xvcjogdmFyKC0tb3JhbmdlKTsgfQogIC5wcm9iLWJhciB7CiAgICB3aWR0aDogMTAwJTsgaGVpZ2h0OiA4cHg7CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1ib3JkZXIpOyBib3JkZXItcmFkaXVzOiA5OTlweDsgb3ZlcmZsb3c6IGhpZGRlbjsKICAgIG1hcmdpbi10b3A6IDAuNXJlbTsKICB9CiAgLnByb2ItZmlsbCB7CiAgICBoZWlnaHQ6IDEwMCU7IGJvcmRlci1yYWRpdXM6IDk5OXB4OwogICAgdHJhbnNpdGlvbjogd2lkdGggMC44cyBlYXNlLCBiYWNrZ3JvdW5kIDAuNXM7CiAgfQoKICAvKiDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAKICAgICBTTElERSA2IOKAlCBDVEEKICDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIDilIAgKi8KICAjczYgewogICAgYmFja2dyb3VuZDogcmFkaWFsLWdyYWRpZW50KGVsbGlwc2UgYXQgNTAlIDUwJSwgcmdiYSgyNTUsOTIsMCwwLjA3KSAwJSwgdHJhbnNwYXJlbnQgNjUlKSwgdmFyKC0tYmcpOwogIH0KCiAgLmN0YS13cmFwIHsgdGV4dC1hbGlnbjogY2VudGVyOyBtYXgtd2lkdGg6IDcwMHB4OyB9CiAgLmN0YS10aXRsZSB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogY2xhbXAoMi41cmVtLCA1dncsIDQuNXJlbSk7CiAgICBmb250LXdlaWdodDogNzAwOyBsaW5lLWhlaWdodDogMS4wNTsKICAgIGxldHRlci1zcGFjaW5nOiAtMC4wMmVtOwogICAgbWFyZ2luLWJvdHRvbTogMS41cmVtOwogIH0KICAuY3RhLXRpdGxlIC5hY2NlbnQgeyBjb2xvcjogdmFyKC0tb3JhbmdlKTsgfQogIC5jdGEtc3ViIHsKICAgIGZvbnQtc2l6ZTogMXJlbTsgY29sb3I6IHZhcigtLW11dGVkKTsgbGluZS1oZWlnaHQ6IDEuNjsKICAgIG1hcmdpbi1ib3R0b206IDNyZW07CiAgfQogIC5kZWxpdmVyYWJsZXMgewogICAgZGlzcGxheTogZmxleDsgZ2FwOiAxcmVtOyBqdXN0aWZ5LWNvbnRlbnQ6IGNlbnRlcjsKICAgIGZsZXgtd3JhcDogd3JhcDsgbWFyZ2luLWJvdHRvbTogM3JlbTsKICB9CiAgLmRlbGktY2FyZCB7CiAgICBwYWRkaW5nOiAxcmVtIDEuMjVyZW07CiAgICBib3JkZXI6IDFweCBzb2xpZCB2YXIoLS1ib3JkZXIpOwogICAgYm9yZGVyLXJhZGl1czogMTJweDsgYmFja2dyb3VuZDogdmFyKC0tc3VyZmFjZSk7CiAgICBtaW4td2lkdGg6IDE1MHB4OwogIH0KICAuZGVsaS1jYXJkIC5kZWxpLWljb24geyBmb250LXNpemU6IDEuNXJlbTsgbWFyZ2luLWJvdHRvbTogMC40cmVtOyB9CiAgLmRlbGktY2FyZCAuZGVsaS1sYWJlbCB7CiAgICBmb250LWZhbWlseTogdmFyKC0tZm9udC1kaXNwbGF5KTsKICAgIGZvbnQtc2l6ZTogMC44cmVtOyBmb250LXdlaWdodDogNjAwOwogIH0KICAuZGVsaS1jYXJkIC5kZWxpLXN1YiB7IGZvbnQtc2l6ZTogMC43cmVtOyBjb2xvcjogdmFyKC0tbXV0ZWQpOyBtYXJnaW4tdG9wOiAwLjJyZW07IH0KCiAgLmN0YS1idG4gewogICAgZGlzcGxheTogaW5saW5lLWZsZXg7IGFsaWduLWl0ZW1zOiBjZW50ZXI7IGdhcDogMC42cmVtOwogICAgcGFkZGluZzogMXJlbSAyLjVyZW07CiAgICBiYWNrZ3JvdW5kOiB2YXIoLS1vcmFuZ2UpOwogICAgY29sb3I6ICNmZmY7IGZvbnQtZmFtaWx5OiB2YXIoLS1mb250LWRpc3BsYXkpOwogICAgZm9udC1zaXplOiAwLjlyZW07IGZvbnQtd2VpZ2h0OiA2MDA7CiAgICBib3JkZXItcmFkaXVzOiA5OTlweDsgYm9yZGVyOiBub25lOyBjdXJzb3I6IHBvaW50ZXI7CiAgICBsZXR0ZXItc3BhY2luZzogMC4wNWVtOwogICAgdHJhbnNpdGlvbjogdHJhbnNmb3JtIDAuMnMsIGJveC1zaGFkb3cgMC4yczsKICAgIHRleHQtZGVjb3JhdGlvbjogbm9uZTsKICB9CiAgLmN0YS1idG46aG92ZXIgewogICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC0ycHgpOwogICAgYm94LXNoYWRvdzogMCA4cHggMzBweCByZ2JhKDI1NSw5MiwwLDAuMzUpOwogIH0KCiAgLyog4pSA4pSAIFBST0dSRVNTIExJTkUg4pSA4pSAICovCiAgLnByb2dyZXNzLWxpbmUgewogICAgcG9zaXRpb246IGZpeGVkOyB0b3A6IDA7IGxlZnQ6IDA7CiAgICBoZWlnaHQ6IDJweDsgYmFja2dyb3VuZDogdmFyKC0tb3JhbmdlKTsKICAgIHRyYW5zaXRpb246IHdpZHRoIDAuNXMgZWFzZTsKICAgIHotaW5kZXg6IDIwMDsKICB9CgogIC8qIOKUgOKUgCBLRVlCT0FSRCBISU5UIOKUgOKUgCAqLwogIC5rYi1oaW50IHsKICAgIHBvc2l0aW9uOiBmaXhlZDsgYm90dG9tOiAycmVtOyBsZWZ0OiAyLjVyZW07CiAgICBmb250LXNpemU6IDAuNjVyZW07IGNvbG9yOiB2YXIoLS1ib3JkZXIpOwogICAgZm9udC1mYW1pbHk6IHZhcigtLWZvbnQtZGlzcGxheSk7CiAgICBsZXR0ZXItc3BhY2luZzogMC4wOGVtOwogIH0KPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KCjwhLS0gTG9nbyAtLT4KPGRpdiBjbGFzcz0ibG9nby1iYXIiPgogIDxkaXYgY2xhc3M9ImxvZ28taWNvbiI+4pqZPC9kaXY+CiAgPGRpdiBjbGFzcz0ibG9nby10ZXh0Ij5QdW1wPGVtPkd1YXJkPC9lbT4gQUk8L2Rpdj4KPC9kaXY+Cgo8IS0tIFByb2dyZXNzIC0tPgo8ZGl2IGNsYXNzPSJwcm9ncmVzcy1saW5lIiBpZD0icHJvZ3Jlc3MiPjwvZGl2PgoKPCEtLSBDb3VudGVyIC0tPgo8ZGl2IGNsYXNzPSJzbGlkZS1jb3VudGVyIiBpZD0iY291bnRlciI+PHNwYW4+MDE8L3NwYW4+IC8gMDY8L2Rpdj4KCjwhLS0gS2V5Ym9hcmQgaGludCAtLT4KPGRpdiBjbGFzcz0ia2ItaGludCI+4oaQIOKGkiBvIENMSUNLIHBhcmEgbmF2ZWdhcjwvZGl2PgoKPCEtLSBOYXYgZG90cyAtLT4KPGRpdiBjbGFzcz0ibmF2IiBpZD0iZG90cyI+PC9kaXY+Cgo8IS0tIEFycm93cyAtLT4KPGRpdiBjbGFzcz0ibmF2LWFycm93cyI+CiAgPGJ1dHRvbiBjbGFzcz0iYnRuLW5hdiIgaWQ9ImJ0bi1wcmV2IiBvbmNsaWNrPSJnbygtMSkiPuKGkDwvYnV0dG9uPgogIDxidXR0b24gY2xhc3M9ImJ0bi1uYXYiIGlkPSJidG4tbmV4dCIgb25jbGljaz0iZ28oMSkiPuKGkjwvYnV0dG9uPgo8L2Rpdj4KCjwhLS0g4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQ4pWQCiAgICAgU0xJREVTCuKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkOKVkCAtLT4KPGRpdiBjbGFzcz0iZGVjayI+CgogIDwhLS0gU0xJREUgMSDigJQgSEVSTyAtLT4KICA8ZGl2IGNsYXNzPSJzbGlkZSBhY3RpdmUiIGlkPSJzMSI+CiAgICA8ZGl2IHN0eWxlPSJ0ZXh0LWFsaWduOmNlbnRlcjsgZGlzcGxheTpmbGV4OyBmbGV4LWRpcmVjdGlvbjpjb2x1bW47IGFsaWduLWl0ZW1zOmNlbnRlcjsiPgogICAgICA8ZGl2IGNsYXNzPSJoZXJvLWV5ZWJyb3ciPkludGVsaWdlbmNpYSBBcnRpZmljaWFsIEluZHVzdHJpYWw8L2Rpdj4KICAgICAgPGgxIGNsYXNzPSJoZXJvLXRpdGxlIj4KICAgICAgICBEZXRlY3RhIGZhbGxvczxicj4KICAgICAgICA8c3BhbiBjbGFzcz0iYWNjZW50Ij5hbnRlczwvc3Bhbj4gZGUgcXVlIG9jdXJyYW48c3BhbiBjbGFzcz0iZGltIj4uPC9zcGFuPgogICAgICA8L2gxPgogICAgICA8cCBjbGFzcz0iaGVyby1zdWIiPgogICAgICAgIFVuIG1vZGVsbyBYR0Jvb3N0IGRlIHByb2R1Y2Npw7NuIHF1ZSBhbmFsaXphIHR1cyBzZW5zb3JlcyBlbiB0aWVtcG8gcmVhbAogICAgICAgIHkgY2xhc2lmaWNhIGNhZGEgbGVjdHVyYSBjb21vIDxzdHJvbmc+Tk9STUFMPC9zdHJvbmc+IG8gPHN0cm9uZz5BbsOzbWFsbzwvc3Ryb25nPgogICAgICAgIGNvbiBwcm9iYWJpbGlkYWRlcyBjYWxpYnJhZGFzLgogICAgICA8L3A+CiAgICAgIDxkaXYgY2xhc3M9ImdhdWdlLXdyYXAiPgogICAgICAgIDxjYW52YXMgaWQ9ImdhdWdlQ2FudmFzIiB3aWR0aD0iMjIwIiBoZWlnaHQ9IjEzMCI+PC9jYW52YXM+CiAgICAgICAgPGRpdiBjbGFzcz0iZ2F1Z2UtdmFsdWUiIGlkPSJnYXVnZVZhbCI+LS08L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJnYXVnZS1sYWJlbCI+UHJvYi4gQW5vbWFsw61hPC9kaXY+CiAgICAgIDwvZGl2PgogICAgICA8ZGl2IGNsYXNzPSJoZXJvLXRhZ3MiPgogICAgICAgIDxkaXYgY2xhc3M9InRhZyI+WEdCb29zdDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InRhZyI+VGllbXBvIFJlYWw8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJ0YWciPlByb2R1Y2Npw7NuPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0idGFnIj5Fc2NhbGFibGU8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJ0YWciPlNpbiByZWVzY2FsYWRvPC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgPC9kaXY+CgogIDwhLS0gU0xJREUgMiDigJQgUFJPQkxFTUEgLS0+CiAgPGRpdiBjbGFzcz0ic2xpZGUiIGlkPSJzMiI+CiAgICA8ZGl2IGNsYXNzPSJ0d28tY29sIj4KICAgICAgPGRpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJoZXJvLWV5ZWJyb3ciIHN0eWxlPSJqdXN0aWZ5LWNvbnRlbnQ6ZmxleC1zdGFydDsiPkVsIFByb2JsZW1hPC9kaXY+CiAgICAgICAgPGgyIGNsYXNzPSJzZWN0aW9uLXRpdGxlIj4KICAgICAgICAgIEVsIGZhbGxvIHNpbGVuY2lvc288YnI+ZGVqYSBtdW5pY2lwaW9zIDxzcGFuIGNsYXNzPSJvcmFuZ2UiPnNpbiBhZ3VhPC9zcGFuPgogICAgICAgIDwvaDI+CiAgICAgICAgPGRpdiBjbGFzcz0ic3RhdC1zdGFjayI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJiaWctc3RhdCI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im51bSI+NSBkw61hczwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJsYWJlbCI+c2luIGFndWE6IGVsIGNvc3RvIHJlYWwgZGUgdW5hIGZhbGxhIG5vIGRldGVjdGFkYSBhIHRpZW1wbyBlbiBlbCBBY3VlZHVjdG8gQ29zdGVybyAoVXNpYWN1csOtLCAyMDIyKTwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkaXZpZGVyLWgiPjwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iYmlnLXN0YXQiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJudW0iPjcwJTwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJsYWJlbCI+ZGUgbG9zIGZhbGxvcyBlbiBib21iYXMgZGUgcmVib21iZW8gcHVlZGVuIGRldGVjdGFyc2UgYW50ZXMgZGUgb2N1cnJpciDigJQgc2kgYW5hbGl6YXMgbG9zIGRhdG9zIGRlbCBzZW5zb3I8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0icGFpbi1saXN0Ij4KICAgICAgICA8ZGl2IGNsYXNzPSJwYWluLWl0ZW0iPgogICAgICAgICAgPGRpdiBjbGFzcz0icGFpbi1pY29uIj7imqDvuI88L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9InBhaW4tdGV4dCI+CiAgICAgICAgICAgIDxzdHJvbmc+TWFudGVuaW1pZW50byByZWFjdGl2bzwvc3Ryb25nPgogICAgICAgICAgICA8c3Bhbj5Tb2xvIGFjdMO6YXMgY3VhbmRvIGxhIGJvbWJhIHlhIGZhbGzDsyDigJQgZWwgbXVuaWNpcGlvIHlhIGxsZXZhIGhvcmFzIHNpbiBhZ3VhLjwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InBhaW4taXRlbSI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJwYWluLWljb24iPvCfk4k8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9InBhaW4tdGV4dCI+CiAgICAgICAgICAgIDxzdHJvbmc+NTIgc2Vuc29yZXMgc2luIGFuYWxpemFyPC9zdHJvbmc+CiAgICAgICAgICAgIDxzcGFuPkVsIHNpc3RlbWEgcmVnaXN0cmEgZGF0b3MgY2FkYSBtaW51dG8sIHBlcm8gbmFkaWUgZGV0ZWN0YSBsYXMgc2XDsWFsZXMgdGVtcHJhbmFzIGRlIGZhbGxhLjwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InBhaW4taXRlbSI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJwYWluLWljb24iPvCflIc8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9InBhaW4tdGV4dCI+CiAgICAgICAgICAgIDxzdHJvbmc+U2luIGFsZXJ0YXMgaW50ZWxpZ2VudGVzPC9zdHJvbmc+CiAgICAgICAgICAgIDxzcGFuPkxvcyB1bWJyYWxlcyBlc3TDoXRpY29zIGdlbmVyYW4gZmFsc2FzIGFsYXJtYXMgbyBwZW9yLCBzaWxlbmNpbyBhbnRlcyBkZWwgY29sYXBzbyBkZSBsYSBlc3RhY2nDs24uPC9zcGFuPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0icGFpbi1pdGVtIj4KICAgICAgICAgIDxkaXYgY2xhc3M9InBhaW4taWNvbiI+4puT77iPPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJwYWluLXRleHQiPgogICAgICAgICAgICA8c3Ryb25nPkVmZWN0byBkb21pbsOzIGVuIGNhZGVuYTwvc3Ryb25nPgogICAgICAgICAgICA8c3Bhbj43IGVzdGFjaW9uZXMgZW4gc2VyaWU6IHNpIHVuYSBmYWxsYSwgdG9kbyBlbCBzaXN0ZW1hIGFndWFzIGFycmliYSBzZSBkZXRpZW5lLjwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgIDwvZGl2PgogIDwvZGl2PgoKICA8IS0tIFNMSURFIDMg4oCUIFNPTFVDScOTTiAtLT4KICA8ZGl2IGNsYXNzPSJzbGlkZSIgaWQ9InMzIj4KICAgIDxkaXYgc3R5bGU9IndpZHRoOjEwMCU7IG1heC13aWR0aDo4NjBweDsgdGV4dC1hbGlnbjpjZW50ZXI7Ij4KICAgICAgPGRpdiBjbGFzcz0iaGVyby1leWVicm93IiBzdHlsZT0ianVzdGlmeS1jb250ZW50OmNlbnRlcjsiPkxhIFNvbHVjacOzbjwvZGl2PgogICAgICA8aDIgY2xhc3M9InNlY3Rpb24tdGl0bGUiPgogICAgICAgIFVuIG1vZGVsbyBxdWUgPHNwYW4gY2xhc3M9ImdyZWVuIj5hcHJlbmRlPC9zcGFuPiBkZSB0dXMgNTIgc2Vuc29yZXMKICAgICAgPC9oMj4KICAgICAgPGRpdiBjbGFzcz0ic29sdXRpb24tZ3JpZCI+CiAgICAgICAgPGRpdiBjbGFzcz0ic29sLWNhcmQiPgogICAgICAgICAgPGRpdiBjbGFzcz0ic29sLWljb24iPvCfp6A8L2Rpdj4KICAgICAgICAgIDxoMz5YR0Jvb3N0IOKAlCBNZWpvciBNb2RlbG88L2gzPgogICAgICAgICAgPHA+RXZhbHVhZG8gY29udHJhIFJhbmRvbSBGb3Jlc3QsIFJlZ3Jlc2nDs24gTG9nw61zdGljYSB5IEtOTi4gWEdCb29zdCBnYW7DsyBlbiBGMS1TY29yZSwgQVVDIHkgdmVsb2NpZGFkIGRlIGluZmVyZW5jaWEuPC9wPgogICAgICAgICAgPHNwYW4gY2xhc3M9ImJhZGdlIj5GMSDiiaUgMC45ODwvc3Bhbj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtY2FyZCI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtaWNvbiI+8J+OrzwvZGl2PgogICAgICAgICAgPGgzPjMgTml2ZWxlcyBkZSBBbGVydGE8L2gzPgogICAgICAgICAgPHA+Tm8gc29sbyAibm9ybWFsIG8gZmFsbG8iIOKAlCBwcm9iYWJpbGlkYWRlcyBjYWxpYnJhZGFzIHBhcmEgcHJpb3JpemFyIGludGVydmVuY2lvbmVzIHBvciBuaXZlbCBkZSByaWVzZ28gcmVhbC48L3A+CiAgICAgICAgICA8c3BhbiBjbGFzcz0iYmFkZ2UiPvCfn6Ig8J+foSDwn5S0PC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9InNvbC1jYXJkIj4KICAgICAgICAgIDxkaXYgY2xhc3M9InNvbC1pY29uIj7imqE8L2Rpdj4KICAgICAgICAgIDxoMz5JbnRlZ3JhY2nDs24gSW5tZWRpYXRhPC9oMz4KICAgICAgICAgIDxwPkFQSSBsaXN0YSBwYXJhIGNvbmVjdGFyIGEgdHUgZGFzaGJvYXJkIERhc2ggZXhpc3RlbnRlLiA1IGzDrW5lYXMgZGUgY8OzZGlnbyBwYXJhIGFjdGl2YXIgcHJlZGljY2lvbmVzIGVuIHZpdm8uPC9wPgogICAgICAgICAgPHNwYW4gY2xhc3M9ImJhZGdlIj5QbHVnICYgUGxheTwvc3Bhbj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtY2FyZCI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtaWNvbiI+8J+UjTwvZGl2PgogICAgICAgICAgPGgzPkdyaWRTZWFyY2ggKyBWYWxpZGFjacOzbiBDcnV6YWRhPC9oMz4KICAgICAgICAgIDxwPkhpcGVycGFyw6FtZXRyb3Mgb3B0aW1pemFkb3MgY29uIEdyaWRTZWFyY2hDVi4gRWwgbW9kZWxvIG5vIHNlIGVudHJlbsOzIHVuYSB2ZXog4oCUIHNlIGJ1c2PDsyBsYSBtZWpvciBjb25maWd1cmFjacOzbiBwb3NpYmxlLjwvcD4KICAgICAgICAgIDxzcGFuIGNsYXNzPSJiYWRnZSI+T3B0aW1pemFkbzwvc3Bhbj4KICAgICAgICA8L2Rpdj4KICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtY2FyZCI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJzb2wtaWNvbiI+8J+UgTwvZGl2PgogICAgICAgICAgPGgzPlJlZW50cmVuYW1pZW50byBTaW1wbGU8L2gzPgogICAgICAgICAgPHA+Q29uIG51ZXZvcyBkYXRvcyBkZSBzZW5zb3IsIGVqZWN1dGFzIHVuIHNjcmlwdCB5IGVsIG1vZGVsbyBzZSBhY3R1YWxpemEuIExhIG1lam9yYSBlcyBjb250aW51YSB5IGF1dG9tw6F0aWNhLjwvcD4KICAgICAgICAgIDxzcGFuIGNsYXNzPSJiYWRnZSI+U2VsZi1pbXByb3Zpbmc8L3NwYW4+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0ic29sLWNhcmQiPgogICAgICAgICAgPGRpdiBjbGFzcz0ic29sLWljb24iPvCfk6Y8L2Rpdj4KICAgICAgICAgIDxoMz5BcnRlZmFjdG9zIExpc3RvczwvaDM+CiAgICAgICAgICA8cD5Nb2RlbG8sIHNjYWxlciwgbWV0YWRhdG9zIHkgZmVhdHVyZXMgZW1wYXF1ZXRhZG9zLiBEZXBsb3kgZW4gY3VhbHF1aWVyIHNlcnZpZG9yIGVuIG1pbnV0b3MuPC9wPgogICAgICAgICAgPHNwYW4gY2xhc3M9ImJhZGdlIj5Qcm9kdWN0aW9uLXJlYWR5PC9zcGFuPgogICAgICAgIDwvZGl2PgogICAgICA8L2Rpdj4KICAgICAgPGRpdiBjbGFzcz0icGlwZWxpbmUiPgogICAgICAgIDxzcGFuIGNsYXNzPSJwaXBlLXN0ZXAiPlNlbnNvcmVzIENTVjwvc3Bhbj4KICAgICAgICA8c3BhbiBjbGFzcz0icGlwZS1hcnJvdyI+4oaSPC9zcGFuPgogICAgICAgIDxzcGFuIGNsYXNzPSJwaXBlLXN0ZXAiPkludGVycG9sYWNpw7NuPC9zcGFuPgogICAgICAgIDxzcGFuIGNsYXNzPSJwaXBlLWFycm93Ij7ihpI8L3NwYW4+CiAgICAgICAgPHNwYW4gY2xhc3M9InBpcGUtc3RlcCBoaWdobGlnaHQiPlhHQm9vc3Q8L3NwYW4+CiAgICAgICAgPHNwYW4gY2xhc3M9InBpcGUtYXJyb3ciPuKGkjwvc3Bhbj4KICAgICAgICA8c3BhbiBjbGFzcz0icGlwZS1zdGVwIj5Qcm9iYWJpbGlkYWQ8L3NwYW4+CiAgICAgICAgPHNwYW4gY2xhc3M9InBpcGUtYXJyb3ciPuKGkjwvc3Bhbj4KICAgICAgICA8c3BhbiBjbGFzcz0icGlwZS1zdGVwIj5BbGVydGEg8J+UtDwvc3Bhbj4KICAgICAgICA8c3BhbiBjbGFzcz0icGlwZS1hcnJvdyI+4oaSPC9zcGFuPgogICAgICAgIDxzcGFuIGNsYXNzPSJwaXBlLXN0ZXAiPkFjY2nDs248L3NwYW4+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgPC9kaXY+CgogIDwhLS0gU0xJREUgNCDigJQgTcOJVFJJQ0FTIC0tPgogIDxkaXYgY2xhc3M9InNsaWRlIiBpZD0iczQiPgogICAgPGRpdiBjbGFzcz0ibWV0cmljcy1sYXlvdXQiPgogICAgICA8ZGl2PgogICAgICAgIDxkaXYgY2xhc3M9Imhlcm8tZXllYnJvdyIgc3R5bGU9Imp1c3RpZnktY29udGVudDpmbGV4LXN0YXJ0OyI+UmVuZGltaWVudG88L2Rpdj4KICAgICAgICA8aDIgY2xhc3M9InNlY3Rpb24tdGl0bGUiIHN0eWxlPSJtYXJnaW4tYm90dG9tOjEuNXJlbTsiPgogICAgICAgICAgTsO6bWVyb3MgcXVlPGJyPjxzcGFuIGNsYXNzPSJncmVlbiI+cmVzcGFsZGFuPC9zcGFuPjxicj5sYSBkZWNpc2nDs24KICAgICAgICA8L2gyPgogICAgICAgIDxwIHN0eWxlPSJmb250LXNpemU6MC44MnJlbTsgY29sb3I6dmFyKC0tbXV0ZWQpOyBsaW5lLWhlaWdodDoxLjY7IG1heC13aWR0aDoyODBweDsiPgogICAgICAgICAgRXZhbHVhZG8gc29icmUgMjIwLjMyMCByZWdpc3Ryb3MgcmVhbGVzIGRlIHNlbnNvciAoYWJy4oCTYWdvIDIwMTgpLiBDb25qdW50byBkZSBwcnVlYmEgZXN0cmF0aWZpY2Fkby4gWEdCb29zdCBzdXBlcsOzIGEgUmFuZG9tIEZvcmVzdCwgUmVncmVzacOzbiBMb2fDrXN0aWNhIHkgS05OLgogICAgICAgIDwvcD4KICAgICAgPC9kaXY+CiAgICAgIDxkaXY+CiAgICAgICAgPGRpdiBjbGFzcz0ibWV0cmljLWNhcmRzIj4KICAgICAgICAgIDxkaXYgY2xhc3M9Im0tY2FyZCI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0tdmFsIiBpZD0ibTEiPi0tPC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0taW5mbyI+CiAgICAgICAgICAgICAgPHN0cm9uZz5GMS1TY29yZSDigJQgWEdCb29zdDwvc3Ryb25nPgogICAgICAgICAgICAgIDxzcGFuPkJhbGFuY2Ugw7NwdGltbyBlbnRyZSBwcmVjaXNpw7NuIHkgcmVjYWxsIMK3IG1lam9yIG1vZGVsbyBldmFsdWFkbzwvc3Bhbj4KICAgICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9Im0tY2FyZCI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0tdmFsIiBpZD0ibTIiPi0tPC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0taW5mbyI+CiAgICAgICAgICAgICAgPHN0cm9uZz5ST0MtQVVDPC9zdHJvbmc+CiAgICAgICAgICAgICAgPHNwYW4+Q2FwYWNpZGFkIGRpc2NyaW1pbmF0b3JpYSBwYXJhIHNlcGFyYXIgTk9STUFMIHZzIEFuw7NtYWxvPC9zcGFuPgogICAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0ibS1jYXJkIiBzdHlsZT0iYm9yZGVyLWNvbG9yOiByZ2JhKDAsMjMyLDEyMiwwLjMpOyI+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0tdmFsIiBpZD0ibTMiPi0tPC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9Im0taW5mbyI+CiAgICAgICAgICAgICAgPHN0cm9uZz5TZW5zb3JlcyBkZSBlbnRyYWRhPC9zdHJvbmc+CiAgICAgICAgICAgICAgPHNwYW4+VmFyaWFibGVzIHNpbXVsdMOhbmVhcyBhbmFsaXphZGFzIGVuIGNhZGEgcHJlZGljY2nDs248L3NwYW4+CiAgICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iYmFyLWNoYXJ0IiBzdHlsZT0ibWFyZ2luLXRvcDoxLjVyZW07Ij4KICAgICAgICAgIDxoND5JbXBvcnRhbmNpYSBkZSBzZW5zb3JlcyBjbGF2ZTwvaDQ+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItcm93Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYmFyLW5hbWUiPnNlbnNvcl8xMTwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItdHJhY2siPjxkaXYgY2xhc3M9ImJhci1maWxsIGJhci1maWxsLTEiIHN0eWxlPSJiYWNrZ3JvdW5kOiB2YXIoLS1ncmVlbik7Ij48L2Rpdj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYmFyLXBjdCIgc3R5bGU9ImNvbG9yOnZhcigtLWdyZWVuKTsiPjkxJTwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItcm93Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYmFyLW5hbWUiPnNlbnNvcl8wNDwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItdHJhY2siPjxkaXYgY2xhc3M9ImJhci1maWxsIGJhci1maWxsLTIiIHN0eWxlPSJiYWNrZ3JvdW5kOiB2YXIoLS1ncmVlbik7Ij48L2Rpdj48L2Rpdj4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYmFyLXBjdCIgc3R5bGU9ImNvbG9yOnZhcigtLWdyZWVuKTsiPjc4JTwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItcm93Ij4KICAgICAgICAgICAgPGRpdiBjbGFzcz0iYmFyLW5hbWUiPnNlbnNvcl8wMDwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItdHJhY2siPjxkaXYgY2xhc3M9ImJhci1maWxsIGJhci1maWxsLTMiIHN0eWxlPSJiYWNrZ3JvdW5kOiB2YXIoLS15ZWxsb3cpOyI+PC9kaXY+PC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJhci1wY3QiIHN0eWxlPSJjb2xvcjp2YXIoLS15ZWxsb3cpOyI+NjMlPC9kaXY+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImJhci1yb3ciPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItbmFtZSI+c2Vuc29yXzA3PC9kaXY+CiAgICAgICAgICAgIDxkaXYgY2xhc3M9ImJhci10cmFjayI+PGRpdiBjbGFzcz0iYmFyLWZpbGwgYmFyLWZpbGwtNCIgc3R5bGU9ImJhY2tncm91bmQ6IHZhcigtLW11dGVkKTsiPjwvZGl2PjwvZGl2PgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJiYXItcGN0IiBzdHlsZT0iY29sb3I6dmFyKC0tbXV0ZWQpOyI+NDUlPC9kaXY+CiAgICAgICAgICA8L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICA8L2Rpdj4KICA8L2Rpdj4KCiAgPCEtLSBTTElERSA1IOKAlCBERU1PIEVOIFZJVk8gLS0+CiAgPGRpdiBjbGFzcz0ic2xpZGUiIGlkPSJzNSI+CiAgICA8ZGl2IHN0eWxlPSJ3aWR0aDoxMDAlOyBtYXgtd2lkdGg6ODYwcHg7Ij4KICAgICAgPGRpdiBjbGFzcz0iaGVyby1leWVicm93IiBzdHlsZT0ianVzdGlmeS1jb250ZW50OmNlbnRlcjsiPkRlbW88L2Rpdj4KICAgICAgPGgyIGNsYXNzPSJzZWN0aW9uLXRpdGxlIiBzdHlsZT0idGV4dC1hbGlnbjpjZW50ZXI7IG1hcmdpbi1ib3R0b206MC41cmVtOyI+CiAgICAgICAgQXPDrSBzZSB2ZSBlbiA8c3BhbiBjbGFzcz0ib3JhbmdlIj5wcm9kdWNjacOzbjwvc3Bhbj4KICAgICAgPC9oMj4KICAgICAgPHAgc3R5bGU9InRleHQtYWxpZ246Y2VudGVyOyBjb2xvcjp2YXIoLS1tdXRlZCk7IGZvbnQtc2l6ZTowLjgycmVtOyBtYXJnaW4tYm90dG9tOjEuNXJlbTsiPgogICAgICAgIFNpbXVsYWNpw7NuIGVuIHZpdm8g4oCUIGVsIG1vZGVsbyBjbGFzaWZpY2EgbGVjdHVyYXMgZGUgc2Vuc29yZXMgZW4gdGllbXBvIHJlYWwKICAgICAgPC9wPgogICAgICA8ZGl2IGNsYXNzPSJhbGVydC1kZW1vIj4KICAgICAgICA8ZGl2IGNsYXNzPSJhbGVydC1wYW5lbCI+CiAgICAgICAgICA8aDQ+8J+ToSBMb2cgZGUgbGVjdHVyYXM8L2g0PgogICAgICAgICAgPGRpdiBjbGFzcz0iYWxlcnQtbG9nIiBpZD0iYWxlcnRMb2ciPjwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9Im91dHB1dC1wYW5lbCI+CiAgICAgICAgICA8aDQ+8J+UjSDDmmx0aW1hIHByZWRpY2Npw7NuPC9oND4KICAgICAgICAgIDxkaXYgY2xhc3M9Im91dC1yb3ciPgogICAgICAgICAgICA8c3BhbiBjbGFzcz0ib3V0LWtleSI+UHJlZGljY2nDs248L3NwYW4+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJvdXQtdmFsIiBpZD0icHJlZFZhbCIgc3R5bGU9ImNvbG9yOnZhcigtLW11dGVkKTsiPuKAlDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0ib3V0LXJvdyI+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJvdXQta2V5Ij5Qcm9iYWJpbGlkYWQ8L3NwYW4+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJvdXQtdmFsIiBpZD0icHJvYlZhbCIgc3R5bGU9ImNvbG9yOnZhcigtLW11dGVkKTsiPuKAlDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0icHJvYi1iYXIiPgogICAgICAgICAgICA8ZGl2IGNsYXNzPSJwcm9iLWZpbGwiIGlkPSJwcm9iRmlsbCIgc3R5bGU9IndpZHRoOjAlOyBiYWNrZ3JvdW5kOnZhcigtLWdyZWVuKTsiPjwvZGl2PgogICAgICAgICAgPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJvdXQtcm93IiBzdHlsZT0ibWFyZ2luLXRvcDowLjVyZW07Ij4KICAgICAgICAgICAgPHNwYW4gY2xhc3M9Im91dC1rZXkiPk5pdmVsIGFsZXJ0YTwvc3Bhbj4KICAgICAgICAgICAgPHNwYW4gY2xhc3M9Im91dC12YWwiIGlkPSJhbGVydFZhbCIgc3R5bGU9ImNvbG9yOnZhcigtLW11dGVkKTsiPuKAlDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0ib3V0LXJvdyI+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJvdXQta2V5Ij5TZW5zb3IgYWN0aXZvPC9zcGFuPgogICAgICAgICAgICA8c3BhbiBjbGFzcz0ib3V0LXZhbCIgaWQ9InNlbnNvclZhbCIgc3R5bGU9ImNvbG9yOnZhcigtLW11dGVkKTsgZm9udC1zaXplOjAuN3JlbTsiPuKAlDwvc3Bhbj4KICAgICAgICAgIDwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0ib3V0LXJvdyI+CiAgICAgICAgICAgIDxzcGFuIGNsYXNzPSJvdXQta2V5Ij5UaWVtcG8gcHJvY2Vzbzwvc3Bhbj4KICAgICAgICAgICAgPHNwYW4gY2xhc3M9Im91dC12YWwiIGlkPSJ0aW1lVmFsIiBzdHlsZT0iY29sb3I6dmFyKC0tbXV0ZWQpOyI+4oCUPC9zcGFuPgogICAgICAgICAgPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgIDwvZGl2PgogICAgPC9kaXY+CiAgPC9kaXY+CgogIDwhLS0gU0xJREUgNiDigJQgQ1RBIC0tPgogIDxkaXYgY2xhc3M9InNsaWRlIiBpZD0iczYiPgogICAgPGRpdiBjbGFzcz0iY3RhLXdyYXAiPgogICAgICA8ZGl2IGNsYXNzPSJoZXJvLWV5ZWJyb3ciIHN0eWxlPSJqdXN0aWZ5LWNvbnRlbnQ6Y2VudGVyOyI+wr9RdcOpIGluY2x1eWU/PC9kaXY+CiAgICAgIDxoMiBjbGFzcz0iY3RhLXRpdGxlIj4KICAgICAgICBEZSBkYXRvcyBhPGJyPjxzcGFuIGNsYXNzPSJhY2NlbnQiPmRlY2lzaW9uZXM8L3NwYW4+PGJyPmhveSBtaXNtbwogICAgICA8L2gyPgogICAgICA8cCBjbGFzcz0iY3RhLXN1YiI+CiAgICAgICAgRW50cmVnYW1vcyB1biBzaXN0ZW1hIGxpc3RvIHBhcmEgcHJvZHVjY2nDs24sIGRvY3VtZW50YWRvLCBpbnRlZ3JhYmxlCiAgICAgICAgY29uIHR1IGluZnJhZXN0cnVjdHVyYSBhY3R1YWwuIFNpbiBjYWphcyBuZWdyYXMsIHNpbiBkZXBlbmRlbmNpYXMgb2N1bHRhcy4KICAgICAgPC9wPgogICAgICA8ZGl2IGNsYXNzPSJkZWxpdmVyYWJsZXMiPgogICAgICAgIDxkaXYgY2xhc3M9ImRlbGktY2FyZCI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkZWxpLWljb24iPvCfpJY8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktbGFiZWwiPk1vZGVsbyBYR0Jvb3N0PC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkZWxpLXN1YiI+RW50cmVuYWRvICYgb3B0aW1pemFkbzwvZGl2PgogICAgICAgIDwvZGl2PgogICAgICAgIDxkaXYgY2xhc3M9ImRlbGktY2FyZCI+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkZWxpLWljb24iPvCfk4o8L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktbGFiZWwiPkRhc2hib2FyZCBEYXNoPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkZWxpLXN1YiI+SW50ZWdyYWNpw7NuIGxpc3RhPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1jYXJkIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktaWNvbiI+8J+TljwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1sYWJlbCI+RG9jdW1lbnRhY2nDs248L2Rpdj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktc3ViIj5SRUFETUUgKyBzY3JpcHRzPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1jYXJkIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktaWNvbiI+8J+UgTwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1sYWJlbCI+UmVlbnRyZW5hbWllbnRvPC9kaXY+CiAgICAgICAgICA8ZGl2IGNsYXNzPSJkZWxpLXN1YiI+U2NyaXB0IGluY2x1aWRvPC9kaXY+CiAgICAgICAgPC9kaXY+CiAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1jYXJkIj4KICAgICAgICAgIDxkaXYgY2xhc3M9ImRlbGktaWNvbiI+8J+OrzwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1sYWJlbCI+MyBuaXZlbGVzIGFsZXJ0YTwvZGl2PgogICAgICAgICAgPGRpdiBjbGFzcz0iZGVsaS1zdWIiPkNhbGlicmFkb3MgYSB0dSByaWVzZ288L2Rpdj4KICAgICAgICA8L2Rpdj4KICAgICAgPC9kaXY+CiAgICAgIDxhIGNsYXNzPSJjdGEtYnRuIiBocmVmPSJtYWlsdG86Y29udGFjdG9AZWplbXBsby5jb20iPgogICAgICAgIOKciSBJbmljaWFyIHByb3llY3RvIGFob3JhCiAgICAgIDwvYT4KICAgIDwvZGl2PgogIDwvZGl2PgoKPC9kaXY+PCEtLSAvZGVjayAtLT4KCjxzY3JpcHQ+Ci8vIOKUgOKUgCBTVEFURSDilIDilIAKbGV0IGN1cnJlbnQgPSAwOwpjb25zdCB0b3RhbCA9IDY7CmxldCBzaW11bEludGVydmFsID0gbnVsbDsKCi8vIOKUgOKUgCBET1RTIOKUgOKUgApjb25zdCBkb3RzRWwgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZG90cycpOwpmb3IgKGxldCBpID0gMDsgaSA8IHRvdGFsOyBpKyspIHsKICBjb25zdCBkID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7CiAgZC5jbGFzc05hbWUgPSAnZG90JyArIChpPT09MD8nIGFjdGl2ZSc6JycpOwogIGQub25jbGljayA9ICgpID0+IGdvVG8oaSk7CiAgZG90c0VsLmFwcGVuZENoaWxkKGQpOwp9CgpmdW5jdGlvbiB1cGRhdGVEb3RzKCkgewogIFsuLi5kb3RzRWwuY2hpbGRyZW5dLmZvckVhY2goKGQsaSkgPT4gZC5jbGFzc0xpc3QudG9nZ2xlKCdhY3RpdmUnLCBpPT09Y3VycmVudCkpOwp9CmZ1bmN0aW9uIHVwZGF0ZUNvdW50ZXIoKSB7CiAgY29uc3QgcyA9IFN0cmluZyhjdXJyZW50KzEpLnBhZFN0YXJ0KDIsJzAnKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnY291bnRlcicpLmlubmVySFRNTCA9IGA8c3Bhbj4ke3N9PC9zcGFuPiAvIDAke3RvdGFsfWA7Cn0KZnVuY3Rpb24gdXBkYXRlUHJvZ3Jlc3MoKSB7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3Byb2dyZXNzJykuc3R5bGUud2lkdGggPSAoKGN1cnJlbnQrMSkvdG90YWwqMTAwKSArICclJzsKfQoKZnVuY3Rpb24gZ29UbyhpZHgpIHsKICBpZiAoaWR4IDwgMCB8fCBpZHggPj0gdG90YWwgfHwgaWR4ID09PSBjdXJyZW50KSByZXR1cm47CiAgY29uc3Qgc2xpZGVzID0gZG9jdW1lbnQucXVlcnlTZWxlY3RvckFsbCgnLnNsaWRlJyk7CiAgc2xpZGVzW2N1cnJlbnRdLmNsYXNzTGlzdC5yZW1vdmUoJ2FjdGl2ZScpOwogIHNsaWRlc1tjdXJyZW50XS5jbGFzc0xpc3QuYWRkKCdleGl0Jyk7CiAgc2V0VGltZW91dCgoKSA9PiBzbGlkZXNbY3VycmVudF0uY2xhc3NMaXN0LnJlbW92ZSgnZXhpdCcpLCA2MDApOwogIGN1cnJlbnQgPSBpZHg7CiAgc2xpZGVzW2N1cnJlbnRdLmNsYXNzTGlzdC5hZGQoJ2FjdGl2ZScpOwogIHVwZGF0ZURvdHMoKTsgdXBkYXRlQ291bnRlcigpOyB1cGRhdGVQcm9ncmVzcygpOwogIG9uU2xpZGVFbnRlcihjdXJyZW50KTsKfQoKZnVuY3Rpb24gZ28oZGlyKSB7IGdvVG8oY3VycmVudCArIGRpcik7IH0KCmRvY3VtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2tleWRvd24nLCBlID0+IHsKICBpZiAoZS5rZXkgPT09ICdBcnJvd1JpZ2h0JyB8fCBlLmtleSA9PT0gJyAnKSBnbygxKTsKICBpZiAoZS5rZXkgPT09ICdBcnJvd0xlZnQnKSBnbygtMSk7Cn0pOwoKLy8g4pSA4pSAIEdBVUdFIChzbGlkZSAxKSDilIDilIAKY29uc3QgZ2F1Z2VDYW52YXMgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZ2F1Z2VDYW52YXMnKTsKY29uc3QgY3R4ID0gZ2F1Z2VDYW52YXMuZ2V0Q29udGV4dCgnMmQnKTsKbGV0IGdhdWdlUHJvYiA9IDA7CmxldCBnYXVnZVRhcmdldCA9IDA7CmxldCBnYXVnZURpciA9IDE7CmxldCBnYXVnZUFuaW1GcmFtZTsKCmZ1bmN0aW9uIGRyYXdHYXVnZShwcm9iKSB7CiAgY29uc3Qgdz0yMjAsIGg9MTMwLCBjeD0xMTAsIGN5PTExMCwgcj05MDsKICBjdHguY2xlYXJSZWN0KDAsMCx3LGgpOwogIGNvbnN0IHN0YXJ0QSA9IE1hdGguUEk7CiAgY29uc3QgZW5kQSA9IDIqTWF0aC5QSTsKCiAgLy8gVHJhY2sKICBjdHguYmVnaW5QYXRoKCk7CiAgY3R4LmFyYyhjeCxjeSxyLHN0YXJ0QSxlbmRBKTsKICBjdHguc3Ryb2tlU3R5bGUgPSAnIzFFMUUyRSc7CiAgY3R4LmxpbmVXaWR0aCA9IDE0OwogIGN0eC5saW5lQ2FwID0gJ3JvdW5kJzsKICBjdHguc3Ryb2tlKCk7CgogIC8vIEZpbGwg4oCUIGNvbG9yIGJ5IHpvbmUKICBjb25zdCBhbmdsZSA9IHN0YXJ0QSArIChwcm9iLzEwMCkqTWF0aC5QSTsKICBsZXQgY29sb3I7CiAgaWYgKHByb2IgPCAzMCkgY29sb3IgPSAnIzAwRTg3QSc7CiAgZWxzZSBpZiAocHJvYiA8IDYwKSBjb2xvciA9ICcjRkZEMTAwJzsKICBlbHNlIGNvbG9yID0gJyNGRjVDMDAnOwoKICBjdHguYmVnaW5QYXRoKCk7CiAgY3R4LmFyYyhjeCxjeSxyLHN0YXJ0QSxhbmdsZSk7CiAgY3R4LnN0cm9rZVN0eWxlID0gY29sb3I7CiAgY3R4LmxpbmVXaWR0aCA9IDE0OwogIGN0eC5saW5lQ2FwID0gJ3JvdW5kJzsKICBjdHguc3Ryb2tlKCk7CgogIC8vIE5lZWRsZQogIGNvbnN0IG5lZWRsZUEgPSBzdGFydEEgKyAocHJvYi8xMDApKk1hdGguUEk7CiAgY3R4LnNhdmUoKTsKICBjdHgudHJhbnNsYXRlKGN4LGN5KTsKICBjdHgucm90YXRlKG5lZWRsZUEpOwogIGN0eC5iZWdpblBhdGgoKTsKICBjdHgubW92ZVRvKC04LDApOyBjdHgubGluZVRvKHItMjAsMCk7CiAgY3R4LnN0cm9rZVN0eWxlID0gJyNmZmYnOwogIGN0eC5saW5lV2lkdGggPSAyOwogIGN0eC5saW5lQ2FwID0gJ3JvdW5kJzsKICBjdHguc3Ryb2tlKCk7CiAgY3R4LmJlZ2luUGF0aCgpOwogIGN0eC5hcmMoMCwwLDUsMCwyKk1hdGguUEkpOwogIGN0eC5maWxsU3R5bGUgPSAnI2ZmZic7CiAgY3R4LmZpbGwoKTsKICBjdHgucmVzdG9yZSgpOwoKICAvLyBWYWx1ZQogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdnYXVnZVZhbCcpLnRleHRDb250ZW50ID0gTWF0aC5yb3VuZChwcm9iKSArICclJzsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnZ2F1Z2VWYWwnKS5zdHlsZS5jb2xvciA9IGNvbG9yOwp9CgpmdW5jdGlvbiBhbmltYXRlR2F1Z2UoKSB7CiAgZ2F1Z2VQcm9iICs9IChnYXVnZVRhcmdldCAtIGdhdWdlUHJvYikgKiAwLjA1OwogIGRyYXdHYXVnZShnYXVnZVByb2IpOwogIGlmIChjdXJyZW50ID09PSAwKSBnYXVnZUFuaW1GcmFtZSA9IHJlcXVlc3RBbmltYXRpb25GcmFtZShhbmltYXRlR2F1Z2UpOwp9CgpmdW5jdGlvbiBzdGFydEdhdWdlTG9vcCgpIHsKICBjYW5jZWxBbmltYXRpb25GcmFtZShnYXVnZUFuaW1GcmFtZSk7CiAgZnVuY3Rpb24gcGlja1RhcmdldCgpIHsKICAgIGdhdWdlVGFyZ2V0ID0gTWF0aC5yYW5kb20oKSAqIDEwMDsKICAgIHNldFRpbWVvdXQocGlja1RhcmdldCwgMjAwMCArIE1hdGgucmFuZG9tKCkqMTUwMCk7CiAgfQogIHBpY2tUYXJnZXQoKTsKICBhbmltYXRlR2F1Z2UoKTsKfQoKLy8g4pSA4pSAIE1FVFJJQ1MgQ09VTlRFUiDilIDilIAKZnVuY3Rpb24gYW5pbWF0ZUNvdW50KGVsLCB0YXJnZXQsIGRlY2ltYWxzLCBzdWZmaXg9JycpIHsKICBsZXQgc3RhcnQgPSAwOwogIGNvbnN0IGR1cmF0aW9uID0gMTIwMDsKICBjb25zdCB0MCA9IHBlcmZvcm1hbmNlLm5vdygpOwogIGZ1bmN0aW9uIHN0ZXAodHMpIHsKICAgIGNvbnN0IHAgPSBNYXRoLm1pbigodHMtdDApL2R1cmF0aW9uLCAxKTsKICAgIGNvbnN0IHZhbCA9IHN0YXJ0ICsgKHRhcmdldC1zdGFydCkqcDsKICAgIGVsLnRleHRDb250ZW50ID0gdmFsLnRvRml4ZWQoZGVjaW1hbHMpICsgc3VmZml4OwogICAgaWYgKHAgPCAxKSByZXF1ZXN0QW5pbWF0aW9uRnJhbWUoc3RlcCk7CiAgICBlbHNlIGVsLnRleHRDb250ZW50ID0gdGFyZ2V0LnRvRml4ZWQoZGVjaW1hbHMpICsgc3VmZml4OwogIH0KICByZXF1ZXN0QW5pbWF0aW9uRnJhbWUoc3RlcCk7Cn0KCmZ1bmN0aW9uIGFuaW1hdGVCYXJzKCkgewogIGNvbnN0IHBjdHMgPSBbOTEsIDc4LCA2MywgNDVdOwogIFsnYmFyLWZpbGwtMScsJ2Jhci1maWxsLTInLCdiYXItZmlsbC0zJywnYmFyLWZpbGwtNCddLmZvckVhY2goKGNscyxpKT0+ewogICAgY29uc3QgZWwgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCcuJytjbHMpOwogICAgaWYgKGVsKSBzZXRUaW1lb3V0KCgpPT57IGVsLnN0eWxlLndpZHRoID0gcGN0c1tpXSsnJSc7IH0sIDIwMCtpKjEwMCk7CiAgfSk7Cn0KCi8vIOKUgOKUgCBMSVZFIERFTU8g4pSA4pSACmNvbnN0IHNlbnNvcnMgPSBbJ3NlbnNvcl8wMCcsJ3NlbnNvcl8wNCcsJ3NlbnNvcl8wNycsJ3NlbnNvcl8xMScsJ3NlbnNvcl8xNCcsJ3NlbnNvcl8wMicsJ3NlbnNvcl8wOSddOwpjb25zdCBzY2VuYXJpb3MgPSBbCiAge3ByZWQ6J05PUk1BTCcsIHByb2I6MTIsIGFsZXJ0Oifwn5+iIEJBSk8nLCBjbHM6J25vcm1hbCd9LAogIHtwcmVkOidOT1JNQUwnLCBwcm9iOjgsICBhbGVydDon8J+foiBCQUpPJywgY2xzOidub3JtYWwnfSwKICB7cHJlZDonTk9STUFMJywgcHJvYjoyNCwgYWxlcnQ6J/Cfn6IgQkFKTycsIGNsczonbm9ybWFsJ30sCiAge3ByZWQ6J0Fuw7NtYWxvJyxwcm9iOjcyLCBhbGVydDon8J+UtCBBTFRPJywgY2xzOidhbHRvJ30sCiAge3ByZWQ6J05PUk1BTCcsIHByb2I6MzgsIGFsZXJ0Oifwn5+hIE1FRElPJywgY2xzOidtZWRpbyd9LAogIHtwcmVkOidBbsOzbWFsbycscHJvYjo4OCwgYWxlcnQ6J/CflLQgQUxUTycsIGNsczonYWx0byd9LAogIHtwcmVkOidOT1JNQUwnLCBwcm9iOjE1LCBhbGVydDon8J+foiBCQUpPJywgY2xzOidub3JtYWwnfSwKICB7cHJlZDonQW7Ds21hbG8nLHByb2I6NTUsIGFsZXJ0Oifwn5+hIE1FRElPJywgY2xzOidtZWRpbyd9LApdOwpsZXQgc2NlbklkeCA9IDA7CmxldCBsb2dFbnRyaWVzID0gW107CgpmdW5jdGlvbiBwdXNoTG9nKHMpIHsKICBjb25zdCBsb2cgPSBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYWxlcnRMb2cnKTsKICBjb25zdCBub3cgPSBuZXcgRGF0ZSgpOwogIGNvbnN0IHRzID0gbm93LnRvVGltZVN0cmluZygpLnNsaWNlKDAsOCk7CiAgY29uc3QgZGl2ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnZGl2Jyk7CiAgZGl2LmNsYXNzTmFtZSA9IGBhbGVydC1lbnRyeSAke3MuY2xzfWA7CiAgZGl2LmlubmVySFRNTCA9IGA8c3BhbiBjbGFzcz0iYWwtdGltZSI+JHt0c308L3NwYW4+IDxzcGFuIGNsYXNzPSJhbC1zdGF0dXMiPiR7cy5wcmVkID09PSAnTk9STUFMJyA/ICfinIUnIDogJ+KaoO+4jyd9ICR7cy5wcmVkfTwvc3Bhbj4gPHNwYW4gc3R5bGU9ImNvbG9yOnZhcigtLW11dGVkKTttYXJnaW4tbGVmdDphdXRvOyI+JHtzLnByb2J9JTwvc3Bhbj5gOwogIGxvZy5wcmVwZW5kKGRpdik7CiAgd2hpbGUgKGxvZy5jaGlsZHJlbi5sZW5ndGggPiA1KSBsb2cucmVtb3ZlQ2hpbGQobG9nLmxhc3RDaGlsZCk7Cn0KCmZ1bmN0aW9uIHVwZGF0ZU91dHB1dChzKSB7CiAgY29uc3Qgc2Vuc29yID0gc2Vuc29yc1tNYXRoLmZsb29yKE1hdGgucmFuZG9tKCkqc2Vuc29ycy5sZW5ndGgpXTsKICBjb25zdCBtcyA9ICgwLjggKyBNYXRoLnJhbmRvbSgpKjIuNCkudG9GaXhlZCgxKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgncHJlZFZhbCcpLnRleHRDb250ZW50ID0gcy5wcmVkOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdwcmVkVmFsJykuY2xhc3NOYW1lID0gJ291dC12YWwgJyArIChzLnByZWQ9PT0nTk9STUFMJz8nbm9ybWFsJzonYW5vbWFsbycpOwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdwcm9iVmFsJykudGV4dENvbnRlbnQgPSBzLnByb2IgKyAnJSc7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ2FsZXJ0VmFsJykudGV4dENvbnRlbnQgPSBzLmFsZXJ0OwogIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhbGVydFZhbCcpLmNsYXNzTmFtZSA9ICdvdXQtdmFsICcgKyBzLmNsczsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnc2Vuc29yVmFsJykudGV4dENvbnRlbnQgPSBzZW5zb3IgKyAnICsgJyArIChzZW5zb3JzLmxlbmd0aC0xKSArICcgbcOhcyc7CiAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ3RpbWVWYWwnKS50ZXh0Q29udGVudCA9IG1zICsgJyBtcyc7CiAgY29uc3QgZmlsbCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdwcm9iRmlsbCcpOwogIGZpbGwuc3R5bGUud2lkdGggPSBzLnByb2IgKyAnJSc7CiAgZmlsbC5zdHlsZS5iYWNrZ3JvdW5kID0gcy5jbHM9PT0nbm9ybWFsJz8ndmFyKC0tZ3JlZW4pJzogcy5jbHM9PT0nbWVkaW8nPyd2YXIoLS15ZWxsb3cpJzondmFyKC0tb3JhbmdlKSc7Cn0KCmZ1bmN0aW9uIHJ1blNpbXVsYXRpb24oKSB7CiAgY29uc3QgcyA9IHNjZW5hcmlvc1tzY2VuSWR4ICUgc2NlbmFyaW9zLmxlbmd0aF07CiAgc2NlbklkeCsrOwogIHB1c2hMb2cocyk7CiAgdXBkYXRlT3V0cHV0KHMpOwp9CgpmdW5jdGlvbiBzdGFydFNpbXVsYXRpb24oKSB7CiAgY2xlYXJJbnRlcnZhbChzaW11bEludGVydmFsKTsKICBkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnYWxlcnRMb2cnKS5pbm5lckhUTUwgPSAnJzsKICBzY2VuSWR4ID0gMDsKICBydW5TaW11bGF0aW9uKCk7CiAgc2ltdWxJbnRlcnZhbCA9IHNldEludGVydmFsKHJ1blNpbXVsYXRpb24sIDE4MDApOwp9CgovLyDilIDilIAgT04gU0xJREUgRU5URVIg4pSA4pSACmZ1bmN0aW9uIG9uU2xpZGVFbnRlcihpZHgpIHsKICBjbGVhckludGVydmFsKHNpbXVsSW50ZXJ2YWwpOwogIGlmIChpZHggPT09IDApIHN0YXJ0R2F1Z2VMb29wKCk7CiAgaWYgKGlkeCA9PT0gMykgewogICAgLy8gbWV0cmljcwogICAgc2V0VGltZW91dCgoKT0+YW5pbWF0ZUNvdW50KGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdtMScpLCAwLjk4LCAyKSwgMjAwKTsKICAgIHNldFRpbWVvdXQoKCk9PmFuaW1hdGVDb3VudChkb2N1bWVudC5nZXRFbGVtZW50QnlJZCgnbTInKSwgMC45OSwgMiksIDQwMCk7CiAgICBzZXRUaW1lb3V0KCgpPT5hbmltYXRlQ291bnQoZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoJ20zJyksIDUyLCAwLCAnIHZhcnMnKSwgNjAwKTsKICAgIGFuaW1hdGVCYXJzKCk7CiAgfQogIGlmIChpZHggPT09IDQpIHN0YXJ0U2ltdWxhdGlvbigpOwp9CgovLyBpbml0CmRyYXdHYXVnZSgwKTsKc3RhcnRHYXVnZUxvb3AoKTsKdXBkYXRlUHJvZ3Jlc3MoKTsKdXBkYXRlQ291bnRlcigpOwo8L3NjcmlwdD4KPC9ib2R5Pgo8L2h0bWw+Cg=="

# --------------------------------------------------------------------------- #
# 4. App Dash
# --------------------------------------------------------------------------- #
app = Dash(
    __name__,
    external_stylesheets=[dbc.themes.FLATLY],
    title="Pump Sensor Dashboard",
    suppress_callback_exceptions=True,
)
server = app.server


def kpi_card(titulo, valor, color="#2c3e50"):
    return dbc.Col(dbc.Card(dbc.CardBody([
        html.H3(valor, className="card-title text-center fw-bold",
                style={"color": color}),
        html.P(titulo, className="card-text text-center text-muted small"),
    ]), className="shadow-sm border-0 h-100"), md=3, className="mb-3")


SENSOR_OPTS = [{"label": s, "value": s} for s in sensores]

app.layout = dbc.Container(fluid=True, children=[

    # ── Encabezado ──────────────────────────────────────────────────────────
    dbc.Row(dbc.Col(html.Div([
        html.H1("Dashboard de Mantenimiento Predictivo",
                className="text-center text-white mb-1 mt-3",
                style={"fontWeight": 700}),
        html.P("EDA completo · XGBoost con validación cruzada · 52 sensores · bomba industrial",
               className="text-center text-white-50 mb-3"),
    ], style={"background": "linear-gradient(135deg,#2c3e50,#3498db)",
              "borderRadius": "10px", "padding": "20px 0"}),
        className="mb-4")),

    # ── KPIs ────────────────────────────────────────────────────────────────
    dbc.Row([
        kpi_card("Registros totales",   f"{N_REGISTROS:,}"),
        kpi_card("Sensores analizados", f"{N_SENSORES}"),
        kpi_card("Eventos BROKEN",      f"{N_FALLAS}", color="#d62728"),
        kpi_card("Periodo",             RANGO),
    ], className="mb-2"),

    # ── Tabs ────────────────────────────────────────────────────────────────
    dbc.Tabs(id="tabs", active_tab="tab-overview", children=[

        # ── 1. VISIÓN GENERAL ──────────────────────────────────────────────
        dbc.Tab(label="📈 Visión General", tab_id="tab-overview", children=[
            dbc.Row(dbc.Col([
                html.Label("Sensor:", className="fw-bold mt-3"),
                dcc.Dropdown(id="ov-sensor", options=SENSOR_OPTS,
                             value="sensor_04", clearable=False),
            ], md=4), className="mt-2"),
            dbc.Row(dbc.Col(dcc.Graph(id="ov-serie"), md=12)),
            dbc.Row([
                dbc.Col(dcc.Graph(id="ov-dist"), md=6),
                dbc.Col(dcc.Graph(id="ov-box"),  md=6),
            ]),
        ]),

        # ── 2. CALIDAD DE DATOS ────────────────────────────────────────────
        dbc.Tab(label="🔍 Calidad de Datos", tab_id="tab-quality", children=[
            dbc.Row([
                dbc.Col([
                    html.H5("Valores Faltantes por Columna", className="mt-3 fw-bold"),
                    dcc.Graph(id="q-missing-bar"),
                ], md=8),
                dbc.Col([
                    html.H5("Resumen General", className="mt-3 fw-bold"),
                    dbc.ListGroup([
                        dbc.ListGroupItem(f"Registros totales: {N_REGISTROS:,}"),
                        dbc.ListGroupItem(f"Duplicados: 0"),
                        dbc.ListGroupItem(
                            f"Columnas con nulos: "
                            f"{(nulos_por_col['nulos'] > 0).sum()}"),
                        dbc.ListGroupItem("sensor_15 — 100 % nulo (eliminado)"),
                        dbc.ListGroupItem(
                            f"sensor_50 — {df_raw['sensor_50'].isnull().mean()*100:.1f} % nulo"),
                    ], flush=True),
                    html.H5("Tipos de Datos", className="mt-4 fw-bold"),
                    dash_table.DataTable(
                        data=tipos_df.to_dict("records"),
                        columns=[{"name": c, "id": c} for c in tipos_df.columns],
                        style_table={"overflowY": "auto", "maxHeight": "300px"},
                        style_cell={"fontSize": 12, "textAlign": "left"},
                        style_header={"fontWeight": "bold",
                                      "background": "#2c3e50", "color": "white"},
                    ),
                ], md=4),
            ]),
            dbc.Row(dbc.Col([
                html.H5("Tabla completa de valores faltantes", className="mt-3 fw-bold"),
                dash_table.DataTable(
                    data=nulos_por_col.to_dict("records"),
                    columns=[{"name": c, "id": c} for c in nulos_por_col.columns],
                    sort_action="native",
                    style_table={"overflowY": "auto", "maxHeight": "350px"},
                    style_cell={"fontSize": 12, "textAlign": "left"},
                    style_header={"fontWeight": "bold",
                                  "background": "#2c3e50", "color": "white"},
                    style_data_conditional=[{
                        "if": {"filter_query": "{porcentaje} > 50"},
                        "backgroundColor": "#fde8e8", "color": "#d62728",
                    }],
                ),
            ])),
        ]),

        # ── 3. ESTADÍSTICA DESCRIPTIVA ─────────────────────────────────────
        dbc.Tab(label="📊 Estadísticas", tab_id="tab-stats", children=[
            dbc.Row([
                dbc.Col([
                    html.H5("Seleccione métrica para comparar sensores",
                            className="mt-3 fw-bold"),
                    dcc.Dropdown(
                        id="st-metric",
                        options=[
                            {"label": "Media",          "value": "mean"},
                            {"label": "Mediana",        "value": "median"},
                            {"label": "Desv. estándar", "value": "std"},
                            {"label": "IQR",            "value": "IQR"},
                            {"label": "Mínimo",         "value": "min"},
                            {"label": "Máximo",         "value": "max"},
                            {"label": "Percentil 95",   "value": "95%"},
                            {"label": "% Faltantes",    "value": "missing%"},
                        ],
                        value="mean", clearable=False),
                ], md=4),
            ]),
            dbc.Row(dbc.Col(dcc.Graph(id="st-bar"))),
            dbc.Row(dbc.Col([
                html.H5("Tabla resumen completa", className="mt-2 fw-bold"),
                dash_table.DataTable(
                    id="st-table",
                    data=desc.round(4).to_dict("records"),
                    columns=[{"name": c, "id": c}
                             for c in ["sensor","count","mean","median","std",
                                       "min","25%","75%","max","IQR",
                                       "missing","missing%"]],
                    sort_action="native", filter_action="native",
                    page_size=20,
                    style_table={"overflowX": "auto"},
                    style_cell={"fontSize": 12, "textAlign": "right",
                                "minWidth": "70px"},
                    style_cell_conditional=[
                        {"if": {"column_id": "sensor"},
                         "textAlign": "left", "fontWeight": "bold"}],
                    style_header={"fontWeight": "bold",
                                  "background": "#2c3e50", "color": "white"},
                ),
            ])),
        ]),

        # ── 4. DISTRIBUCIONES ──────────────────────────────────────────────
        dbc.Tab(label="📉 Distribuciones", tab_id="tab-dist", children=[
            dbc.Row([
                dbc.Col([
                    html.Label("Sensor:", className="fw-bold mt-3"),
                    dcc.Dropdown(id="di-sensor", options=SENSOR_OPTS,
                                 value="sensor_04", clearable=False),
                ], md=4),
                dbc.Col([
                    html.Label("Nº de bins:", className="fw-bold mt-3"),
                    dcc.Slider(id="di-bins", min=10, max=150, step=5,
                               value=60, marks={i: str(i) for i in [10,40,80,120,150]}),
                ], md=6),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="di-hist"),   md=6),
                dbc.Col(dcc.Graph(id="di-violin"), md=6),
            ]),
            dbc.Row(dbc.Col([
                html.H5("Histogramas de todos los sensores (muestra)", className="mt-2 fw-bold"),
                dcc.Graph(id="di-all-hist"),
            ])),
        ]),

        # ── 5. OUTLIERS ────────────────────────────────────────────────────
        dbc.Tab(label="⚠️ Outliers", tab_id="tab-outliers", children=[
            dbc.Row([
                dbc.Col([
                    html.Label("Sensor:", className="fw-bold mt-3"),
                    dcc.Dropdown(id="ou-sensor", options=SENSOR_OPTS,
                                 value="sensor_04", clearable=False),
                ], md=4),
                dbc.Col([
                    html.Label("Factor IQR (k):", className="fw-bold mt-3"),
                    dcc.Slider(id="ou-k", min=1.0, max=4.0, step=0.5,
                               value=1.5,
                               marks={v: str(v) for v in [1.0,1.5,2.0,2.5,3.0,4.0]}),
                ], md=5),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="ou-box"),     md=6),
                dbc.Col(dcc.Graph(id="ou-scatter"), md=6),
            ]),
            dbc.Row(dbc.Col(dcc.Graph(id="ou-summary-bar"))),
        ]),

        # ── 6. CORRELACIONES ───────────────────────────────────────────────
        dbc.Tab(label="🔗 Correlaciones", tab_id="tab-corr", children=[
            dbc.Row(dbc.Col([
                html.H5("Heatmap de correlación entre sensores",
                        className="mt-3 fw-bold"),
                dcc.Graph(id="co-heatmap"),
            ])),
            dbc.Row([
                dbc.Col([
                    html.Label("Sensor X:", className="fw-bold mt-2"),
                    dcc.Dropdown(id="co-x", options=SENSOR_OPTS,
                                 value="sensor_04", clearable=False),
                ], md=3),
                dbc.Col([
                    html.Label("Sensor Y:", className="fw-bold mt-2"),
                    dcc.Dropdown(id="co-y", options=SENSOR_OPTS,
                                 value="sensor_11", clearable=False),
                ], md=3),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="co-scatter"), md=8),
                dbc.Col([
                    html.H5("Top correlaciones", className="mt-3 fw-bold"),
                    dcc.Graph(id="co-top"),
                ], md=4),
            ]),
        ]),

        # ── 7. ANÁLISIS DE CLASES ──────────────────────────────────────────
        dbc.Tab(label="🏷️ Análisis de Clases", tab_id="tab-class", children=[
            dbc.Row([
                dbc.Col([
                    html.Label("Sensor:", className="fw-bold mt-3"),
                    dcc.Dropdown(id="cl-sensor", options=SENSOR_OPTS,
                                 value="sensor_04", clearable=False),
                ], md=4),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="cl-pie"),   md=4),
                dbc.Col(dcc.Graph(id="cl-box"),   md=8),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="cl-violin"),   md=6),
                dbc.Col(dcc.Graph(id="cl-mean-bar"), md=6),
            ]),
            dbc.Row(dbc.Col(dcc.Graph(id="cl-timeline"))),
        ]),

        # ── 8. MODELO ML — XGBoost + Validación Cruzada ───────────────────
        dbc.Tab(label="🤖 Modelo ML (XGBoost)", tab_id="tab-ml", children=[
            dbc.Row([
                dbc.Col([
                    html.H5("XGBoost — Clasificación de Anomalías", className="mt-3 fw-bold"),
                    html.P(
                        "Modelo entrenado con los mejores hiperparámetros identificados en el "
                        "notebook (GridSearchCV): n_estimators=400, max_depth=6, "
                        "learning_rate=0.1, subsample=0.8. "
                        "Split cronológico 80/20 (entrena en el pasado, evalúa en el futuro). "
                        "Validación cruzada estratificada de 5 folds.",
                        className="text-muted small"),
                ], md=12),
            ]),

            # KPIs de métricas
            dbc.Row(id="ml-kpis", className="mt-2 mb-3"),

            # Gráficas: CV scores + Matriz de confusión + Importancias
            dbc.Row([
                dbc.Col(dcc.Graph(id="ml-cv-f1"),  md=6),
                dbc.Col(dcc.Graph(id="ml-cv-auc"), md=6),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="ml-cm"),          md=5),
                dbc.Col(dcc.Graph(id="ml-importancias"), md=7),
            ]),
            dbc.Row([
                dbc.Col(dcc.Graph(id="ml-roc"), md=12),
            ]),
        ]),

        # ── 9. PITCH / PRESENTACIÓN ────────────────────────────────────────
        dbc.Tab(label="🚀 Pitch PumpGuard AI", tab_id="tab-pitch", children=[
            dbc.Row(dbc.Col([
                html.H5("Presentación Comercial — PumpGuard AI",
                        className="mt-3 fw-bold text-center"),
                html.P("Deck de mantenimiento predictivo basado en detección de anomalías con XGBoost.",
                       className="text-center text-muted small mb-2"),
                html.Iframe(
                    src=f"data:text/html;base64,{PITCH_B64}",
                    style={"width": "100%", "height": "85vh",
                           "border": "1px solid #dee2e6", "borderRadius": "8px"},
                ),
            ], md=12)),
        ]),

    ]),  # fin Tabs

    html.Hr(),
    html.P("Fuente: telemetría de bomba (abr–ago 2018) · Dashboard v3.0 — EDA + XGBoost + Pitch",
           className="text-center text-muted small mb-3"),

])  # fin Container


# =========================================================================== #
# CALLBACKS
# =========================================================================== #

# ── TAB 1: Visión General ──────────────────────────────────────────────────
@app.callback(
    Output("ov-serie", "figure"),
    Output("ov-dist",  "figure"),
    Output("ov-box",   "figure"),
    Input("ov-sensor", "value"),
)
def overview(sensor):
    serie = df_hora[sensor]
    fig_s = go.Figure()
    fig_s.add_trace(go.Scatter(x=serie.index, y=serie.values, mode="lines",
                               name=sensor, line=dict(color="#2c7fb8", width=1)))
    for f in FALLAS:
        fig_s.add_vline(x=f, line_dash="dash", line_color="#d62728", opacity=0.6)
    fig_s.update_layout(
        title=f"{sensor} en el tiempo  (líneas rojas = eventos BROKEN)",
        xaxis_title="Tiempo", yaxis_title=sensor,
        template="plotly_white", height=400, margin=dict(l=50,r=20,t=55,b=40))

    fig_d = px.histogram(df, x=sensor, nbins=60, marginal="box",
                         title=f"Distribución de {sensor}",
                         template="plotly_white", color_discrete_sequence=["#2c7fb8"])
    fig_d.update_layout(height=360, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))

    fig_b = px.box(df.reset_index(), x="machine_status", y=sensor,
                   color="machine_status",
                   category_orders={"machine_status": ORDEN_ESTADO},
                   color_discrete_map=COLOR_ESTADO,
                   title=f"{sensor} por estado de máquina", template="plotly_white")
    fig_b.update_layout(height=360, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))
    return fig_s, fig_d, fig_b


# ── TAB 2: Calidad ────────────────────────────────────────────────────────
@app.callback(Output("q-missing-bar", "figure"), Input("tabs", "active_tab"))
def calidad(_):
    fig = px.bar(
        nulos_por_col[nulos_por_col["nulos"] > 0],
        x="columna", y="porcentaje", text="porcentaje",
        color="porcentaje",
        color_continuous_scale=["#2ca02c","#ff7f0e","#d62728"],
        labels={"porcentaje": "% faltante", "columna": "Columna"},
        title="Porcentaje de valores faltantes por columna",
        template="plotly_white",
    )
    fig.update_traces(texttemplate="%{text:.1f}%", textposition="outside")
    fig.update_layout(height=400, coloraxis_showscale=False,
                      margin=dict(l=40,r=20,t=55,b=80))
    return fig


# ── TAB 3: Estadísticas ───────────────────────────────────────────────────
@app.callback(Output("st-bar", "figure"), Input("st-metric", "value"))
def stats_bar(metric):
    tmp = desc[["sensor", metric]].sort_values(metric, ascending=False)
    fig = px.bar(tmp, x="sensor", y=metric, text=metric,
                 color=metric, color_continuous_scale="Blues",
                 title=f"{metric} por sensor", template="plotly_white")
    fig.update_traces(texttemplate="%{text:.3f}", textposition="outside")
    fig.update_layout(height=420, coloraxis_showscale=False,
                      margin=dict(l=40,r=20,t=55,b=80), xaxis_tickangle=-45)
    return fig


# ── TAB 4: Distribuciones ─────────────────────────────────────────────────
@app.callback(
    Output("di-hist",     "figure"),
    Output("di-violin",   "figure"),
    Output("di-all-hist", "figure"),
    Input("di-sensor", "value"),
    Input("di-bins",   "value"),
)
def distribuciones(sensor, bins):
    fig_h = px.histogram(df, x=sensor, nbins=bins, marginal="rug",
                         color_discrete_sequence=["#3498db"],
                         title=f"Histograma de {sensor}", template="plotly_white")
    fig_h.update_layout(height=380, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))

    fig_v = px.violin(df.reset_index(), y=sensor, x="machine_status",
                      color="machine_status",
                      category_orders={"machine_status": ORDEN_ESTADO},
                      color_discrete_map=COLOR_ESTADO, box=True, points=False,
                      title=f"Violín de {sensor} por clase", template="plotly_white")
    fig_v.update_layout(height=380, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))

    s16 = sensores[:16]
    rows, cols = 4, 4
    fig_g = make_subplots(rows=rows, cols=cols,
                          subplot_titles=s16, vertical_spacing=0.08)
    for i, s in enumerate(s16):
        r, c = divmod(i, cols)
        vals = df[s].dropna()
        fig_g.add_trace(
            go.Histogram(x=vals, nbinsx=40, showlegend=False,
                         marker_color=PALETTE[i % len(PALETTE)]),
            row=r+1, col=c+1)
    fig_g.update_layout(height=700, title_text="Distribuciones — primeros 16 sensores",
                        template="plotly_white", margin=dict(l=30,r=20,t=70,b=30))
    return fig_h, fig_v, fig_g


# ── TAB 5: Outliers ───────────────────────────────────────────────────────
@app.callback(
    Output("ou-box",         "figure"),
    Output("ou-scatter",     "figure"),
    Output("ou-summary-bar", "figure"),
    Input("ou-sensor", "value"),
    Input("ou-k",      "value"),
)
def outliers(sensor, k):
    Q1, Q3 = df[sensor].quantile(0.25), df[sensor].quantile(0.75)
    IQR_v  = Q3 - Q1
    lo, hi = Q1 - k * IQR_v, Q3 + k * IQR_v
    mask   = (df[sensor] < lo) | (df[sensor] > hi)
    n_out  = int(mask.sum())

    fig_b = go.Figure()
    fig_b.add_trace(go.Box(y=df[sensor], name=sensor, boxpoints=False,
                           fillcolor="#2c7fb8", line_color="#1a5276"))
    fig_b.add_hline(y=hi, line_dash="dash", line_color="#d62728",
                    annotation_text=f"Límite sup ({hi:.2f})")
    fig_b.add_hline(y=lo, line_dash="dash", line_color="#d62728",
                    annotation_text=f"Límite inf ({lo:.2f})")
    fig_b.update_layout(title=f"Boxplot {sensor} · k={k}  ({n_out} outliers)",
                        template="plotly_white", height=400,
                        margin=dict(l=50,r=20,t=55,b=40))

    s_hora  = df_hora[sensor]
    colores = ["#d62728" if v < lo or v > hi else "#aec6cf"
               for v in s_hora.values]
    fig_sc = go.Figure()
    fig_sc.add_trace(go.Scatter(x=s_hora.index, y=s_hora.values, mode="markers",
                                marker=dict(color=colores, size=3), name=sensor))
    fig_sc.update_layout(title=f"{sensor} — outliers en rojo (k={k})",
                         template="plotly_white", height=400,
                         margin=dict(l=50,r=20,t=55,b=40))

    n_out_all = {}
    for s in sensores:
        q1, q3 = df[s].quantile(0.25), df[s].quantile(0.75)
        iq = q3 - q1
        n_out_all[s] = int(((df[s] < q1 - k*iq) | (df[s] > q3 + k*iq)).sum())
    out_df = (pd.DataFrame.from_dict(n_out_all, orient="index", columns=["n_outliers"])
              .reset_index().rename(columns={"index": "sensor"})
              .sort_values("n_outliers", ascending=False))
    fig_sum = px.bar(out_df, x="sensor", y="n_outliers",
                     color="n_outliers", color_continuous_scale="Reds",
                     title=f"Cantidad de outliers por sensor (k={k})",
                     template="plotly_white")
    fig_sum.update_layout(height=380, coloraxis_showscale=False,
                          margin=dict(l=40,r=20,t=55,b=80), xaxis_tickangle=-45)
    return fig_b, fig_sc, fig_sum


# ── TAB 6: Correlaciones ──────────────────────────────────────────────────
@app.callback(
    Output("co-heatmap", "figure"),
    Output("co-scatter", "figure"),
    Output("co-top",     "figure"),
    Input("co-x", "value"),
    Input("co-y", "value"),
)
def correlaciones(sx, sy):
    fig_h = px.imshow(
        corr_matrix, zmin=-1, zmax=1, color_continuous_scale="RdBu_r",
        title="Matriz de correlación (Pearson)", aspect="auto",
        template="plotly_white",
    )
    fig_h.update_layout(height=600, margin=dict(l=20,r=20,t=55,b=20))

    sample = df[[sx, sy, "machine_status"]].sample(min(5000, len(df)), random_state=42)
    fig_s = px.scatter(
        sample, x=sx, y=sy, color="machine_status",
        color_discrete_map=COLOR_ESTADO, opacity=0.5,
        category_orders={"machine_status": ORDEN_ESTADO},
        title=f"Scatter {sx} vs {sy}  (r = {corr_matrix.loc[sx,sy]:.3f})",
        template="plotly_white",
    )
    x_vals = sample[sx].values
    y_vals = sample[sy].values
    mask_valid = ~(np.isnan(x_vals) | np.isnan(y_vals))
    if mask_valid.sum() > 1:
        m, b = np.polyfit(x_vals[mask_valid], y_vals[mask_valid], 1)
        x_line = np.array([x_vals[mask_valid].min(), x_vals[mask_valid].max()])
        y_line = m * x_line + b
        fig_s.add_trace(go.Scatter(
            x=x_line, y=y_line, mode="lines",
            name="Tendencia", line=dict(color="black", width=2, dash="dash")))
    fig_s.update_layout(height=420, margin=dict(l=40,r=20,t=55,b=40))

    upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
    pairs = (upper.stack()
             .reset_index()
             .rename(columns={"level_0": "s1", "level_1": "s2", 0: "r"})
             .assign(abs_r=lambda x: x["r"].abs())
             .sort_values("abs_r", ascending=False)
             .head(15))
    pairs["par"] = pairs["s1"] + " / " + pairs["s2"]
    fig_t = px.bar(pairs, x="r", y="par", orientation="h",
                   color="r", color_continuous_scale="RdBu_r",
                   range_color=[-1, 1],
                   title="Top 15 pares más correlacionados",
                   template="plotly_white")
    fig_t.update_layout(height=450, coloraxis_showscale=False,
                        margin=dict(l=20,r=20,t=55,b=40))
    return fig_h, fig_s, fig_t


# ── TAB 7: Análisis de Clases ─────────────────────────────────────────────
@app.callback(
    Output("cl-pie",      "figure"),
    Output("cl-box",      "figure"),
    Output("cl-violin",   "figure"),
    Output("cl-mean-bar", "figure"),
    Output("cl-timeline", "figure"),
    Input("cl-sensor", "value"),
)
def clases(sensor):
    df_r = df.reset_index()
    counts = df["machine_status"].value_counts().reset_index()
    counts.columns = ["estado", "n"]
    fig_pie = px.pie(counts, names="estado", values="n",
                     color="estado", color_discrete_map=COLOR_ESTADO,
                     title="Distribución de machine_status", hole=0.4)
    fig_pie.update_layout(height=360, margin=dict(l=20,r=20,t=55,b=20))

    fig_box = px.box(df_r, x="machine_status", y=sensor,
                     color="machine_status",
                     category_orders={"machine_status": ORDEN_ESTADO},
                     color_discrete_map=COLOR_ESTADO, points=False,
                     title=f"{sensor} por clase", template="plotly_white")
    fig_box.update_layout(height=360, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))

    fig_v = px.violin(df_r, y=sensor, x="machine_status",
                      color="machine_status",
                      category_orders={"machine_status": ORDEN_ESTADO},
                      color_discrete_map=COLOR_ESTADO, box=True, points=False,
                      title=f"Violín {sensor} por clase", template="plotly_white")
    fig_v.update_layout(height=360, showlegend=False, margin=dict(l=40,r=20,t=55,b=40))

    means = (df.groupby("machine_status", observed=False)[sensores]
             .mean()
             .T
             .assign(diff=lambda x: x.max(axis=1) - x.min(axis=1))
             .sort_values("diff", ascending=False)
             .head(20))
    means_long = means.drop(columns="diff").reset_index().melt(
        id_vars="index", var_name="estado", value_name="media")
    means_long.columns = ["sensor", "estado", "media"]
    fig_mb = px.bar(means_long, x="sensor", y="media", color="estado",
                    barmode="group", color_discrete_map=COLOR_ESTADO,
                    category_orders={"estado": ORDEN_ESTADO},
                    title="Media por clase — top 20 sensores más discriminativos",
                    template="plotly_white")
    fig_mb.update_layout(height=420, margin=dict(l=40,r=20,t=55,b=80),
                         xaxis_tickangle=-45)

    s_hora = df_hora[sensor].reset_index()
    s_hora.columns = ["timestamp", "valor"]
    s_hora["estado"] = estado_hora.values
    fig_tl = px.scatter(s_hora, x="timestamp", y="valor", color="estado",
                        color_discrete_map=COLOR_ESTADO,
                        category_orders={"estado": ORDEN_ESTADO},
                        title=f"{sensor} en el tiempo coloreado por estado",
                        template="plotly_white", opacity=0.7)
    fig_tl.update_traces(marker_size=3)
    fig_tl.update_layout(height=380, margin=dict(l=50,r=20,t=55,b=40))
    return fig_pie, fig_box, fig_v, fig_mb, fig_tl


# ── TAB 8: Modelo ML — XGBoost ────────────────────────────────────────────
@app.callback(
    Output("ml-kpis",         "children"),
    Output("ml-cv-f1",        "figure"),
    Output("ml-cv-auc",       "figure"),
    Output("ml-cm",           "figure"),
    Output("ml-importancias", "figure"),
    Output("ml-roc",          "figure"),
    Input("tabs", "active_tab"),
)
def ml_tab(_):
    # ── KPI cards ──
    color_map = {
        "F1 (test cronológico)": "#e74c3c",
        "ROC-AUC (test)":        "#2980b9",
        "Precision (test)":      "#27ae60",
        "Recall (test)":         "#8e44ad",
    }
    kpi_items = []
    for k, v in list(ML_METRICAS.items())[:4]:
        color = color_map.get(k, "#2c3e50")
        kpi_items.append(
            dbc.Col(dbc.Card(dbc.CardBody([
                html.H3(str(v), className="card-title text-center fw-bold",
                        style={"color": color}),
                html.P(k, className="card-text text-center text-muted small"),
            ]), className="shadow-sm border-0"), md=3, className="mb-3")
        )

    # ── Gráfica CV F1 por fold ──
    if ML_CV_F1 is not None:
        fig_cv_f1 = go.Figure()
        fig_cv_f1.add_trace(go.Bar(
            x=[f"Fold {i+1}" for i in range(len(ML_CV_F1))],
            y=ML_CV_F1, marker_color="#e74c3c",
            text=[f"{v:.4f}" for v in ML_CV_F1], textposition="outside"))
        fig_cv_f1.add_hline(y=ML_CV_F1.mean(), line_dash="dash",
                             line_color="#c0392b",
                             annotation_text=f"Media={ML_CV_F1.mean():.4f}")
        fig_cv_f1.update_layout(
            title="F1-score por fold (Validación Cruzada 5-Fold Estratificada)",
            yaxis_range=[0, 1.05], template="plotly_white", height=360,
            margin=dict(l=40,r=20,t=55,b=40))

        fig_cv_auc = go.Figure()
        fig_cv_auc.add_trace(go.Bar(
            x=[f"Fold {i+1}" for i in range(len(ML_CV_AUC))],
            y=ML_CV_AUC, marker_color="#2980b9",
            text=[f"{v:.4f}" for v in ML_CV_AUC], textposition="outside"))
        fig_cv_auc.add_hline(y=ML_CV_AUC.mean(), line_dash="dash",
                              line_color="#1a5276",
                              annotation_text=f"Media={ML_CV_AUC.mean():.4f}")
        fig_cv_auc.update_layout(
            title="ROC-AUC por fold (Validación Cruzada 5-Fold Estratificada)",
            yaxis_range=[0.9, 1.01], template="plotly_white", height=360,
            margin=dict(l=40,r=20,t=55,b=40))
    else:
        fig_cv_f1  = go.Figure().update_layout(title="XGBoost no disponible")
        fig_cv_auc = go.Figure().update_layout(title="XGBoost no disponible")

    # ── Matriz de confusión ──
    if ML_CM is not None:
        labels = ["NORMAL", "Anómalo"]
        fig_cm = px.imshow(
            ML_CM, text_auto=True, color_continuous_scale="Blues",
            x=labels, y=labels,
            title="Matriz de Confusión (test cronológico 20 %)",
            labels={"x": "Predicción", "y": "Real"})
        fig_cm.update_layout(height=380, margin=dict(l=50,r=20,t=55,b=50))
    else:
        fig_cm = go.Figure().update_layout(title="Sin datos")

    # ── Importancia de variables (top 20) ──
    if ML_IMPORTANCIAS is not None:
        top20 = ML_IMPORTANCIAS.head(20)
        fig_imp = px.bar(
            x=top20.values, y=top20.index, orientation="h",
            color=top20.values, color_continuous_scale="Oranges",
            title="Top 20 sensores más importantes (XGBoost feature importance)",
            labels={"x": "Importancia", "y": "Sensor"},
            template="plotly_white")
        fig_imp.update_layout(height=500, coloraxis_showscale=False,
                              margin=dict(l=20,r=20,t=55,b=40), yaxis_autorange="reversed")
    else:
        fig_imp = go.Figure().update_layout(title="Sin datos")

    # ── Curva ROC ──
    if ML_OK:
        from sklearn.metrics import roc_curve
        fpr, tpr, _ = roc_curve(y_test_ml, y_proba_ml)
        auc_val = ML_METRICAS.get("ROC-AUC (test)", 0)
        fig_roc = go.Figure()
        fig_roc.add_trace(go.Scatter(x=fpr, y=tpr, mode="lines",
                                     name=f"XGBoost (AUC={auc_val})",
                                     line=dict(color="#e74c3c", width=2)))
        fig_roc.add_trace(go.Scatter(x=[0,1], y=[0,1], mode="lines",
                                     name="Aleatorio",
                                     line=dict(color="gray", dash="dash")))
        fig_roc.update_layout(
            title="Curva ROC — XGBoost (test cronológico)",
            xaxis_title="Tasa de Falsos Positivos",
            yaxis_title="Tasa de Verdaderos Positivos",
            template="plotly_white", height=420,
            margin=dict(l=50,r=20,t=55,b=50))
    else:
        fig_roc = go.Figure().update_layout(title="XGBoost no disponible")

    return kpi_items, fig_cv_f1, fig_cv_auc, fig_cm, fig_imp, fig_roc


# =========================================================================== #
if __name__ == "__main__":
    app.run(debug=True)
